# Generated by Django 5.2.4 on 2025-08-12 16:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0011_unit_is_smart_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_rate', models.DecimalField(decimal_places=2, default=7.5, max_digits=6)),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('peak_start_hour', models.IntegerField(default=17)),
                ('peak_end_hour', models.IntegerField(default=22)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=64)),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, default=Decimal('7.50'), max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CutoffEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Balance depleted', max_length=255)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=20, unique=True)),
                ('power_status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('min_balance_alert', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('min_balance_cutoff', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='LiveReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('overdraft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('voltage_a', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('voltage_b', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('voltage_c', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('current_a', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('current_b', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('current_c', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('total_power', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('power_a', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('power_b', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('power_c', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('pf_total', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('pf_a', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('pf_b', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('pf_c', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('total_energy', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('peak_total_energy', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('valley_total_consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('flat_total_consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('status_word', models.CharField(blank=True, max_length=16, null=True)),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='smart_meter.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('closing_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('units_consumed', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, max_digits=8)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='properties.unit')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='smart_meter.meter')),
            ],
        ),
        migrations.CreateModel(
            name='MeterBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='MeterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('cutoff', 'Power Cut-Off'), ('restore', 'Power Restored'), ('recharge', 'Recharge'), ('payment', 'Payment Recorded'), ('alert', 'Low Balance Alert')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_energy', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('peak_total_energy', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('valley_total_consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('flat_total_consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('total_power', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('pf_total', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('voltage_a', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('voltage_b', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('voltage_c', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('current_a', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('current_b', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('current_c', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='smart_meter.meter')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='smart_meter.bill')),
            ],
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['meter_number'], name='smart_meter_meter_n_7330ff_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['meter', 'ts'], name='smart_meter_meter_i_9ffd4e_idx'),
        ),
    ]
