# Generated by Django 5.2.4 on 2025-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0002_livereading_last2_days_energy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=32, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('last_raw_hex', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('ignored', 'Ignored'), ('added', 'Added')], default='new', max_length=16)),
            ],
        ),
    ]
