# Generated by Django 5.2.4 on 2025-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0003_unknownmeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='name',
            field=models.CharField(default='smart meter', max_length=100),
            preserve_default=False,
        ),
    ]
