# Generated by Django 5.2.4 on 2025-08-15 22:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0004_meter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='service_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=8),
        ),
    ]
