# Generated by Django 5.2.4 on 2025-08-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0005_meter_service_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='livereading',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livereading',
            name='source_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='source_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
