# Generated by Django 5.2.4 on 2025-08-21 21:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0006_livereading_source_ip_livereading_source_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterPrepaidSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_amount_1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('alarm_amount_2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rate1_price_1', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('rate2_price_1', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('step1_value_1', models.PositiveIntegerField(default=0, help_text='kWh in first step (optional)')),
                ('step2_value_1', models.PositiveIntegerField(default=0, help_text='kWh in second step (optional)')),
                ('rate_switch_time', models.BigIntegerField(default=0)),
                ('step_switch_time', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid', to='smart_meter.meter')),
            ],
        ),
    ]
