# Generated by Django 5.2.4 on 2025-10-21 22:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0008_alter_meter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(db_index=True, max_length=32)),
                ('frame_hex', models.TextField()),
                ('expect_di', models.CharField(blank=True, max_length=16)),
                ('timeout', models.FloatField(default=12.0)),
                ('status', models.CharField(choices=[('new', 'New'), ('sent', 'Sent'), ('ok', 'OK'), ('timeout', 'Timeout'), ('error', 'Error')], db_index=True, default='new', max_length=16)),
                ('reply_hex', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('initiated_by', models.CharField(blank=True, max_length=128)),
                ('reason', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_meter.meter')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='smart_meter_status_537326_idx')],
            },
        ),
    ]
