# Generated by Django 5.2.4 on 2026-05-17 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def mark_existing_prepaid_meters(apps, schema_editor):
    Meter = apps.get_model("smart_meter", "Meter")
    MeterPrepaidSettings = apps.get_model("smart_meter", "MeterPrepaidSettings")
    prepaid_meter_ids = MeterPrepaidSettings.objects.values_list("meter_id", flat=True)
    Meter.objects.filter(id__in=prepaid_meter_ids).update(billing_mode="prepaid")


def unmark_existing_prepaid_meters(apps, schema_editor):
    Meter = apps.get_model("smart_meter", "Meter")
    Meter.objects.filter(billing_mode="prepaid").update(billing_mode="postpaid")


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0036_whatsapptemplate'),
        ('properties', '0013_propertymedia_unitmedia'),
        ('smart_meter', '0009_metercommand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='billing_mode',
            field=models.CharField(choices=[('postpaid', 'Postpaid'), ('prepaid', 'Prepaid')], default='postpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='MeterAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_assignment_changes', to='leases.lease')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='smart_meter.meter')),
                ('new_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_meter_assignment_changes', to='leases.lease')),
                ('new_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignment_changes', to='smart_meter.meter')),
                ('new_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_meter_assignment_changes', to='properties.unit')),
                ('old_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_meter_assignment_changes', to='leases.lease')),
                ('old_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assignment_changes', to='smart_meter.meter')),
                ('old_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_meter_assignment_changes', to='properties.unit')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_assignment_changes', to='properties.unit')),
            ],
            options={
                'ordering': ['-change_date', '-id'],
            },
        ),
        migrations.RunPython(mark_existing_prepaid_meters, unmark_existing_prepaid_meters),
    ]
