# Generated by Django 5.2.4 on 2026-05-25 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0038_leaseunitoccupancy'),
        ('properties', '0013_propertymedia_unitmedia'),
        ('smart_meter', '0010_meter_billing_mode_meterassignmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('electric', 'Electric'), ('gas', 'Gas'), ('water', 'Water'), ('sub_meter', 'Sub Meter'), ('other', 'Other')], default='electric', max_length=20),
        ),
        migrations.AlterField(
            model_name='meter',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Cached current unit only. Billing uses MeterInstallation history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_meters', to='properties.unit'),
        ),
        migrations.CreateModel(
            name='MeterInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_reading', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('end_reading', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_installations', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_installations', to='leases.lease')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='smart_meter.meter')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_installations', to='properties.unit')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['meter', 'is_active', 'start_date'], name='smart_meter_meter_i_f8e4d9_idx'), models.Index(fields=['unit', 'is_active', 'start_date'], name='smart_meter_unit_id_6db3ab_idx'), models.Index(fields=['lease', 'start_date'], name='smart_meter_lease_i_e40f82_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='meter_installation_end_after_start'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_active', True)), fields=('meter',), name='one_active_installation_per_meter')],
            },
        ),
    ]
