# Generated by Django 5.2.4 on 2026-05-25 13:15

from django.db import migrations, models


def populate_active_meter_keys(apps, schema_editor):
    MeterInstallation = apps.get_model("smart_meter", "MeterInstallation")
    seen = set()
    for installation in (
        MeterInstallation.objects
        .filter(is_active=True, end_date__isnull=True)
        .order_by("meter_id", "-start_date", "-id")
    ):
        if installation.meter_id in seen:
            continue
        seen.add(installation.meter_id)
        MeterInstallation.objects.filter(pk=installation.pk).update(active_meter_key=installation.meter_id)


def clear_active_meter_keys(apps, schema_editor):
    MeterInstallation = apps.get_model("smart_meter", "MeterInstallation")
    MeterInstallation.objects.update(active_meter_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0012_backfill_meter_installations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meterinstallation',
            name='one_active_installation_per_meter',
        ),
        migrations.AddField(
            model_name='meterinstallation',
            name='active_meter_key',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Internal DB guard: meter id while active, NULL when closed.', null=True, unique=True),
        ),
        migrations.RunPython(populate_active_meter_keys, clear_active_meter_keys),
    ]
