from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smart_meter", "0018_repair_f56_flat_2_meter_installation"),
        ("payments", "0010_rename_allocation_relations_to_payment_detail"),
        ("invoices", "0025_security_deposit_ledger_transfer"),
        ("leases", "0099_leaserenewal_photo_settings"),
        ("tenants", "0030_temporary_registration_upload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="meter",
            name="billing_mode",
            field=models.CharField(
                choices=[
                    ("postpaid", "Postpaid"),
                    ("credit_controlled", "Postpaid with Credit Limit"),
                    ("prepaid", "Prepaid (Legacy)"),
                    ("prepaid_pilot", "DL/T645 Prepaid Pilot"),
                ],
                default="postpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metercommand",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New (legacy)"), ("pending", "Pending"),
                    ("waiting_online", "Waiting for Meter"), ("claimed", "Claimed"),
                    ("sent", "Sent"), ("acknowledged", "Acknowledged"),
                    ("verified", "Verified"), ("retry", "Retry Scheduled"),
                    ("cancelled", "Cancelled"), ("expired", "Expired"),
                    ("failed", "Failed"), ("ok", "OK (legacy)"),
                    ("timeout", "Timeout (legacy)"), ("error", "Error (legacy)"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metercommand",
            name="meter",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name="commands", to="smart_meter.meter",
            ),
        ),
        migrations.AddField(model_name="metercommand", name="command_type", field=models.CharField(choices=[("relay", "Relay"), ("read", "Read"), ("prepaid_read", "Prepaid Read"), ("prepaid_write", "Prepaid Write"), ("prepaid_recharge", "Prepaid Recharge"), ("other", "Other")], db_index=True, default="other", max_length=24)),
        migrations.AddField(model_name="metercommand", name="desired_state", field=models.CharField(blank=True, choices=[("", "Not applicable"), ("on", "On"), ("off", "Off")], default="", max_length=8)),
        migrations.AddField(model_name="metercommand", name="source", field=models.CharField(choices=[("manual", "Manual"), ("credit_control", "Credit Control"), ("payment", "Payment"), ("prepaid", "Prepaid Pilot"), ("system", "System")], db_index=True, default="manual", max_length=24)),
        migrations.AddField(model_name="metercommand", name="priority", field=models.PositiveSmallIntegerField(default=50)),
        migrations.AddField(model_name="metercommand", name="idempotency_key", field=models.CharField(blank=True, max_length=160, null=True, unique=True)),
        migrations.AddField(model_name="metercommand", name="not_before", field=models.DateTimeField(blank=True, db_index=True, null=True)),
        migrations.AddField(model_name="metercommand", name="expires_at", field=models.DateTimeField(blank=True, db_index=True, null=True)),
        migrations.AddField(model_name="metercommand", name="attempt_count", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="metercommand", name="max_attempts", field=models.PositiveIntegerField(default=5)),
        migrations.AddField(model_name="metercommand", name="last_attempt_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="metercommand", name="next_attempt_at", field=models.DateTimeField(blank=True, db_index=True, null=True)),
        migrations.AddField(model_name="metercommand", name="requires_verification", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="metercommand", name="acknowledged_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="metercommand", name="verified_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="metercommand", name="cancelled_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="metercommand", name="cancelled_reason", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="metercommand", name="raw_ack_hex", field=models.TextField(blank=True)),
        migrations.AddField(model_name="metercommand", name="status_query_hex", field=models.TextField(blank=True)),
        migrations.AddField(model_name="metercommand", name="parsed_relay_state", field=models.CharField(blank=True, max_length=16)),
        migrations.AddField(model_name="metercommand", name="related_payment", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_commands", to="payments.payment")),
        migrations.AddField(model_name="metercommand", name="related_invoice", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_commands", to="invoices.invoice")),

        migrations.CreateModel(
            name="MeterCreditAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mode", models.CharField(choices=[("credit_controlled", "Postpaid with Credit Limit")], default="credit_controlled", max_length=24)),
                ("is_enabled", models.BooleanField(db_index=True, default=False)),
                ("active_installation_key", models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ("credit_limit_source", models.CharField(choices=[("fixed", "Fixed monetary limit"), ("deposit_percent", "Percentage of electricity security deposit"), ("lower_of", "Lower of fixed and deposit-derived"), ("lease_override", "Lease-specific manual override")], default="fixed", max_length=24)),
                ("fixed_credit_limit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("deposit_percentage", models.DecimalField(decimal_places=2, default=Decimal("100.00"), max_digits=6)),
                ("lease_override_limit", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("deposit_reference_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("effective_credit_limit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("limit_explanation", models.CharField(blank=True, max_length=255)),
                ("warning_threshold_percent", models.DecimalField(decimal_places=2, default=Decimal("75.00"), max_digits=6)),
                ("final_warning_threshold_percent", models.DecimalField(decimal_places=2, default=Decimal("90.00"), max_digits=6)),
                ("cutoff_threshold_percent", models.DecimalField(decimal_places=2, default=Decimal("100.00"), max_digits=6)),
                ("reconnect_threshold_percent", models.DecimalField(decimal_places=2, default=Decimal("80.00"), max_digits=6)),
                ("reconnect_policy", models.CharField(choices=[("below_reconnect", "Exposure below reconnect threshold"), ("below_cutoff", "Exposure below cutoff threshold"), ("full_balance", "Full enforceable electricity balance paid"), ("minimum_payment", "Minimum fixed payment"), ("staff_approval", "Staff approval required")], default="below_reconnect", max_length=24)),
                ("minimum_reconnect_payment", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("automatic_cutoff", models.BooleanField(default=False)),
                ("automatic_restore", models.BooleanField(default=False)),
                ("manual_only_cutoff", models.BooleanField(default=True)),
                ("staff_approval_required", models.BooleanField(default=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("activation_reading_kwh", models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ("checkpoint_reading_kwh", models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ("checkpoint_at", models.DateTimeField(blank=True, null=True)),
                ("starting_tariff", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("last_evaluated_reading_kwh", models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("accrued_usage_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("previous_unpaid_electricity", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("payments_applied", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("credits_applied", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("current_exposure", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("enforcement_state", models.CharField(choices=[("normal", "Normal"), ("warning_1", "Warning 1"), ("warning_2", "Warning 2"), ("cutoff_eligible", "Cutoff eligible"), ("cutoff_pending", "Cutoff pending"), ("cutoff_sent", "Cutoff sent"), ("disconnected", "Disconnected"), ("reconnect_eligible", "Reconnect eligible"), ("reconnect_pending", "Reconnect pending"), ("reconnect_sent", "Reconnect sent"), ("connected", "Connected"), ("manual_hold", "Manual hold"), ("data_review_required", "Data review required"), ("reading_reset_detected", "Reading reset detected"), ("tariff_missing", "Tariff missing"), ("stale_reading", "Stale reading"), ("installation_mismatch", "Installation mismatch"), ("command_failed", "Command failed")], db_index=True, default="normal", max_length=32)),
                ("data_quality_reason", models.CharField(blank=True, max_length=255)),
                ("last_warning_level", models.PositiveSmallIntegerField(default=0)),
                ("max_consumption_jump_kwh", models.DecimalField(decimal_places=3, default=Decimal("250.000"), max_digits=12)),
                ("stale_after_minutes", models.PositiveIntegerField(default=30)),
                ("notifications_muted_until", models.DateTimeField(blank=True, null=True)),
                ("notifications_muted_for_period", models.CharField(blank=True, max_length=20)),
                ("notification_mute_reason", models.CharField(blank=True, max_length=255)),
                ("notification_muted_at", models.DateTimeField(blank=True, null=True)),
                ("enforcement_hold_until", models.DateTimeField(blank=True, null=True)),
                ("enforcement_hold_for_period", models.CharField(blank=True, max_length=20)),
                ("enforcement_hold_reason", models.CharField(blank=True, max_length=255)),
                ("enforcement_hold_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("installation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="credit_accounts", to="smart_meter.meterinstallation")),
                ("lease", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="meter_credit_accounts", to="leases.lease")),
                ("meter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="credit_accounts", to="smart_meter.meter")),
                ("notifications_muted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_credit_notification_mutes", to=settings.AUTH_USER_MODEL)),
                ("enforcement_hold_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_credit_enforcement_holds", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "permissions": [("view_meter_credit_details", "Can view meter credit details"), ("change_meter_credit_settings", "Can change meter credit settings"), ("activate_meter_credit", "Can activate meter credit control"), ("deactivate_meter_credit", "Can deactivate meter credit control"), ("mute_meter_credit_notifications", "Can mute meter credit notifications"), ("hold_meter_credit_enforcement", "Can hold meter credit enforcement"), ("approve_meter_credit_cutoff", "Can approve meter credit cutoff"), ("override_meter_credit_reconnect", "Can override meter credit reconnection policy"), ("use_meter_credit_emergency_stop", "Can use meter credit emergency stop")],
            },
        ),
        migrations.AddConstraint(model_name="metercreditaccount", constraint=models.CheckConstraint(condition=models.Q(("reconnect_threshold_percent__lte", models.F("cutoff_threshold_percent"))), name="meter_credit_reconnect_lte_cutoff")),
        migrations.AddConstraint(model_name="metercreditaccount", constraint=models.CheckConstraint(condition=models.Q(("warning_threshold_percent__lte", models.F("final_warning_threshold_percent"))), name="meter_credit_warning_order_1")),
        migrations.AddConstraint(model_name="metercreditaccount", constraint=models.CheckConstraint(condition=models.Q(("final_warning_threshold_percent__lte", models.F("cutoff_threshold_percent"))), name="meter_credit_warning_order_2")),
        migrations.AddIndex(model_name="metercreditaccount", index=models.Index(fields=["meter", "is_enabled"], name="smart_meter_meter_i_26e595_idx")),
        migrations.AddIndex(model_name="metercreditaccount", index=models.Index(fields=["installation", "is_enabled"], name="smart_meter_install_27ba23_idx")),
        migrations.AddIndex(model_name="metercreditaccount", index=models.Index(fields=["lease", "is_enabled"], name="smart_meter_lease_i_0f426d_idx")),
        migrations.AddIndex(model_name="metercreditaccount", index=models.Index(fields=["enforcement_state", "is_enabled"], name="smart_meter_enforce_0d6e0c_idx")),

        migrations.CreateModel(
            name="MeterEvaluationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("latest_reading_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("reading_timestamp", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("done", "Done"), ("failed", "Failed")], db_index=True, default="pending", max_length=16)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("meter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_evaluation_requests", to="smart_meter.meter")),
            ],
        ),
        migrations.AddIndex(model_name="meterevaluationrequest", index=models.Index(fields=["status", "created_at"], name="smart_meter_status_4122c3_idx")),
        migrations.AddIndex(model_name="meterevaluationrequest", index=models.Index(fields=["meter", "status"], name="smart_meter_meter_i_17fc3c_idx")),

        migrations.CreateModel(
            name="MeterCreditAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(db_index=True, max_length=64)),
                ("previous_state", models.CharField(blank=True, max_length=64)),
                ("new_state", models.CharField(blank=True, max_length=64)),
                ("exposure_before", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("exposure_after", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("threshold", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("source", models.CharField(choices=[("automatic", "Automatic"), ("scheduled", "Scheduled"), ("manual", "Manual"), ("payment", "Payment"), ("reading", "Reading"), ("system", "System")], default="system", max_length=16)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("credit_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="smart_meter.metercreditaccount")),
                ("installation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="credit_audits", to="smart_meter.meterinstallation")),
                ("invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_credit_audits", to="invoices.invoice")),
                ("lease", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_credit_audits", to="leases.lease")),
                ("meter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="credit_audits", to="smart_meter.meter")),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_credit_audits", to="payments.payment")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_credit_audits", to="tenants.tenant")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meter_credit_audits", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(model_name="metercreditaudit", index=models.Index(fields=["meter", "created_at"], name="smart_meter_meter_i_9258f6_idx")),
        migrations.AddIndex(model_name="metercreditaudit", index=models.Index(fields=["credit_account", "created_at"], name="smart_meter_credit__427e75_idx")),

        migrations.AddField(model_name="metercommand", name="related_credit_account", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="commands", to="smart_meter.metercreditaccount")),
        migrations.AddField(model_name="metercommand", name="related_enforcement_event", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="commands", to="smart_meter.metercreditaudit")),
        migrations.AddIndex(model_name="metercommand", index=models.Index(fields=["meter_number", "status", "priority"], name="smart_meter_meter_n_3fee58_idx")),
        migrations.AddIndex(model_name="metercommand", index=models.Index(fields=["source", "desired_state", "status"], name="smart_meter_source_426201_idx")),
        migrations.AlterModelOptions(name="metercommand", options={"permissions": [("cancel_meter_command", "Can cancel pending meter command"), ("view_raw_dlt645_frames", "Can view raw DL/T645 frames")]}),

        migrations.CreateModel(
            name="MeterPrepaidPilot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("disabled", "Disabled"), ("read_only", "Read only"), ("configuration_pending", "Configuration pending"), ("configuration_sent", "Configuration sent"), ("configuration_verified", "Configuration verified"), ("recharge_pending", "Recharge pending"), ("active_test", "Active test"), ("failed", "Failed"), ("rolled_back", "Rolled back")], db_index=True, default="disabled", max_length=32)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("firmware_version", models.CharField(blank=True, max_length=100)),
                ("display_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enabled_prepaid_pilots", to=settings.AUTH_USER_MODEL)),
                ("installation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="prepaid_pilots", to="smart_meter.meterinstallation")),
                ("meter", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="prepaid_pilot", to="smart_meter.meter")),
            ],
            options={"permissions": [("enable_prepaid_pilot", "Can enable prepaid pilot"), ("read_prepaid_parameters", "Can read prepaid parameters"), ("write_prepaid_parameters", "Can write prepaid parameters"), ("recharge_prepaid_meter", "Can recharge prepaid meter"), ("rollback_prepaid_meter", "Can roll back prepaid meter")]},
        ),
        migrations.CreateModel(
            name="MeterPrepaidParameterRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("di", models.CharField(blank=True, max_length=16)),
                ("parameter", models.CharField(max_length=64)),
                ("raw_response", models.TextField(blank=True)),
                ("parsed_value", models.CharField(blank=True, max_length=128)),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("parse_status", models.CharField(default="pending", max_length=24)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("pilot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parameter_reads", to="smart_meter.meterprepaidpilot")),
            ],
        ),
        migrations.CreateModel(
            name="MeterPrepaidWriteAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("parameter", models.CharField(max_length=64)),
                ("requested_value", models.CharField(max_length=128)),
                ("original_value", models.CharField(blank=True, max_length=128)),
                ("read_before_hex", models.TextField(blank=True)),
                ("command_hex", models.TextField(blank=True)),
                ("ack_hex", models.TextField(blank=True)),
                ("read_back_hex", models.TextField(blank=True)),
                ("actual_value", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("verified", "Verified"), ("failed", "Failed"), ("rolled_back", "Rolled back")], default="pending", max_length=16)),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("pilot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="write_attempts", to="smart_meter.meterprepaidpilot")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prepaid_write_attempts", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="MeterPrepaidRecharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_id", models.CharField(max_length=64, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("manufacturer_sequence", models.CharField(blank=True, max_length=64)),
                ("before_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("after_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("status", models.CharField(choices=[("disabled", "Disabled"), ("pending", "Pending"), ("verified", "Verified"), ("failed", "Failed"), ("uncertain", "Uncertain")], default="disabled", max_length=16)),
                ("reconciliation_note", models.TextField(blank=True)),
                ("raw_command", models.TextField(blank=True)),
                ("raw_ack", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prepaid_recharges", to=settings.AUTH_USER_MODEL)),
                ("pilot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recharges", to="smart_meter.meterprepaidpilot")),
            ],
        ),
    ]
