# Generated by Django 5.2.4 on 2026-08-16 10:16

from django.db import migrations, models


def clear_legacy_default_rate(apps, schema_editor):
    Meter = apps.get_model("smart_meter", "Meter")
    Meter.objects.filter(unit_rate=50).update(unit_rate=None)


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0019_meter_credit_control_core'),
        ('core', '0029_alter_globalsettings_unit_rate_per_kwh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, help_text='Optional meter electricity-rate override. Override order: Global, Property, Unit, Meter, then Lease; the last nonblank value wins.', max_digits=10, null=True),
        ),
        migrations.RunPython(clear_legacy_default_rate, migrations.RunPython.noop),
    ]
