# Generated by Django 5.2.4 on 2026-08-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0031_energy_system_meter_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metercommand',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('credit_control', 'Credit Control'), ('payment', 'Payment'), ('prepaid', 'Prepaid Pilot'), ('system', 'System'), ('schedule', 'Timing Schedule'), ('energy_probe', 'Energy Probe (No Persistence)'), ('energy_probe_persist', 'Energy Probe (Persist)'), ('energy_auto_poll', 'Automatic Bidirectional Energy Poll')], db_index=True, default='manual', max_length=24),
        ),
    ]
