# Generated by Django 5.2.4 on 2026-09-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0034_meterrawframe'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meterrawframe',
            new_name='smart_meter_meter_i_30ab4d_idx',
            old_name='smart_meter_meter_i_80bb74_idx',
        ),
        migrations.RenameIndex(
            model_name='meterrawframe',
            new_name='smart_meter_meter_i_bdc997_idx',
            old_name='smart_meter_meter_i_d1be52_idx',
        ),
    ]
