# Generated by Django 5.2.4 on 2026-09-07 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def classify_existing_meter_tariffs(apps, schema_editor):
    Meter = apps.get_model('smart_meter', 'Meter')
    for meter in Meter.objects.all().only('pk', 'meter_number').iterator():
        number = str(meter.meter_number or '').strip()
        capability = 'unknown' if not number else (
            'single_rate' if number.startswith('26') else 'multi_rate'
        )
        Meter.objects.filter(pk=meter.pk).update(tariff_capability=capability)


def reset_meter_tariff_capabilities(apps, schema_editor):
    apps.get_model('smart_meter', 'Meter').objects.update(tariff_capability='unknown')


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0035_rename_smart_meter_meter_i_80bb74_idx_smart_meter_meter_i_30ab4d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='tariff_capability',
            field=models.CharField(choices=[('single_rate', 'Single-rate'), ('multi_rate', 'Multi-rate'), ('unknown', 'Unknown / not confirmed')], db_index=True, default='unknown', help_text='Single-rate copies one price to all tariff slots. Multi-rate can use a flat price or multiple scheduled rates. Unknown disables tariff writes.', max_length=16),
        ),
        migrations.RunPython(
            classify_existing_meter_tariffs,
            reset_meter_tariff_capabilities,
        ),
        migrations.AlterField(
            model_name='metercommand',
            name='command_type',
            field=models.CharField(choices=[('relay', 'Relay'), ('read', 'Read'), ('tariff_read', 'Tariff Read'), ('tariff_write', 'Tariff Write'), ('prepaid_read', 'Prepaid Read'), ('prepaid_write', 'Prepaid Write'), ('prepaid_recharge', 'Prepaid Recharge'), ('other', 'Other')], db_index=True, default='other', max_length=24),
        ),
        migrations.AlterField(
            model_name='metercommand',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('credit_control', 'Credit Control'), ('payment', 'Payment'), ('prepaid', 'Prepaid Pilot'), ('system', 'System'), ('schedule', 'Timing Schedule'), ('energy_probe', 'Energy Probe (No Persistence)'), ('energy_probe_persist', 'Energy Probe (Persist)'), ('energy_auto_poll', 'Automatic Bidirectional Energy Poll'), ('tariff', 'Tariff Configuration')], db_index=True, default='manual', max_length=24),
        ),
        migrations.CreateModel(
            name='MeterTariffAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('single_rate', 'Single-rate'), ('multi_rate', 'Multi-rate'), ('unknown', 'Unknown / not confirmed')], max_length=16)),
                ('configuration_type', models.CharField(choices=[('read', 'Read'), ('flat', 'Flat tariff'), ('time_of_use', 'Time-of-use tariff'), ('schedule_draft', 'Schedule draft'), ('schedule_write', 'Schedule write')], max_length=20)),
                ('values_before', models.JSONField(blank=True, default=dict)),
                ('requested_values', models.JSONField(blank=True, default=dict)),
                ('values_after', models.JSONField(blank=True, default=dict)),
                ('raw_read_before_frame', models.TextField(blank=True)),
                ('raw_write_frame', models.TextField(blank=True)),
                ('raw_write_reply_frame', models.TextField(blank=True)),
                ('raw_read_back_frame', models.TextField(blank=True)),
                ('command_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('not_configured', 'Not configured'), ('read', 'Live configuration read'), ('draft', 'Draft'), ('offline_queued', 'Offline / queued / not verified'), ('sent_pending_verification', 'Sent pending verification'), ('verified', 'Verified'), ('no_change', 'No change'), ('failed', 'Failed'), ('unsafe_readback', 'Unsafe read-back')], db_index=True, max_length=32)),
                ('error', models.TextField(blank=True)),
                ('submission_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiating_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_tariff_audits', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_audits', to='smart_meter.meter')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeterTariffBulkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial')], db_index=True, default='draft', max_length=16)),
                ('submission_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_tariff_bulk_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeterTariffBulkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('single_rate', 'Single-rate'), ('multi_rate', 'Multi-rate'), ('unknown', 'Unknown / not confirmed')], max_length=16)),
                ('status', models.CharField(choices=[('not_configured', 'Not configured'), ('read', 'Live configuration read'), ('draft', 'Draft'), ('offline_queued', 'Offline / queued / not verified'), ('sent_pending_verification', 'Sent pending verification'), ('verified', 'Verified'), ('no_change', 'No change'), ('failed', 'Failed'), ('unsafe_readback', 'Unsafe read-back')], default='not_configured', max_length=32)),
                ('old_prices', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='smart_meter.metertariffaudit')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_bulk_items', to='smart_meter.meter')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smart_meter.metertariffbulkrun')),
            ],
        ),
        migrations.CreateModel(
            name='MeterTariffConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('flat', 'Flat'), ('time_of_use', 'Time-of-use')], default='', max_length=16)),
                ('active_rate_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate_1_label', models.CharField(default='Valley', max_length=64)),
                ('rate_2_label', models.CharField(default='Flat', max_length=64)),
                ('rate_3_label', models.CharField(default='Peak', max_length=64)),
                ('rate_4_label', models.CharField(default='Shoulder', max_length=64)),
                ('rate_1_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rate_2_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rate_3_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rate_4_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('schedule_draft', models.JSONField(blank=True, default=list)),
                ('latest_verified_schedule_summary', models.JSONField(blank=True, default=list)),
                ('last_configuration_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('not_configured', 'Not configured'), ('read', 'Live configuration read'), ('draft', 'Draft'), ('offline_queued', 'Offline / queued / not verified'), ('sent_pending_verification', 'Sent pending verification'), ('verified', 'Verified'), ('no_change', 'No change'), ('failed', 'Failed'), ('unsafe_readback', 'Unsafe read-back')], db_index=True, default='not_configured', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_configuration', to='smart_meter.meter')),
            ],
            options={
                'permissions': [('read_meter_tariff', 'Can read meter tariff configuration'), ('write_meter_tariff', 'Can write meter tariff configuration'), ('bulk_write_meter_tariff', 'Can configure meter tariffs in bulk'), ('view_meter_tariff_audit', 'Can view meter tariff audit history')],
            },
        ),
        migrations.AddIndex(
            model_name='metertariffaudit',
            index=models.Index(fields=['meter', '-created_at'], name='smart_meter_meter_i_f44956_idx'),
        ),
        migrations.AddConstraint(
            model_name='metertariffbulkitem',
            constraint=models.UniqueConstraint(fields=('run', 'meter'), name='uniq_tariff_bulk_run_meter'),
        ),
    ]
