# Generated by Django 5.2.4 on 2026-09-10 14:28

import django.db.models.deletion
from django.db import migrations, models


def enable_prepaid_controls(apps, schema_editor):
    MeterSettings = apps.get_model("smart_meter", "MeterSettings")
    MeterSettings.objects.update_or_create(
        pk=1,
        defaults={
            "prepaid_reads_enabled": True,
            "prepaid_writes_enabled": True,
            "prepaid_payment_topups_enabled": True,
        },
    )


def disable_prepaid_controls(apps, schema_editor):
    MeterSettings = apps.get_model("smart_meter", "MeterSettings")
    MeterSettings.objects.filter(pk=1).update(
        prepaid_reads_enabled=False,
        prepaid_writes_enabled=False,
        prepaid_payment_topups_enabled=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paymentdetail_electricity_amount_and_more'),
        ('smart_meter', '0038_harden_tariff_bulk_idempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='metersettings',
            name='prepaid_payment_topups_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metersettings',
            name='prepaid_reads_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metersettings',
            name='prepaid_writes_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MeterPrepaidPaymentTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_payment_detail_id', models.PositiveBigIntegerField(unique=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('verified', 'Verified'), ('uncertain', 'Uncertain'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_topups', to='smart_meter.meter')),
                ('payment_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_meter_topups', to='payments.paymentdetail')),
                ('recharge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_topup', to='smart_meter.meterprepaidrecharge')),
            ],
        ),
        migrations.RunPython(enable_prepaid_controls, disable_prepaid_controls),
    ]
