# Generated by Django 5.2.4 on 2026-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0039_database_prepaid_controls_and_payment_topups'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Authoritative meter-reported prepaid balance at this reading.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='overdraft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Resolved electricity rate snapshot used to explain balance movement.', max_digits=10, null=True),
        ),
    ]
