# Generated by Django 5.2.4 on 2026-09-17 22:52

import django.db.models.deletion
from datetime import date
from django.db import migrations, models


def seed_audit_assignments(apps, schema_editor):
    Group = apps.get_model('smart_meter', 'MeterCheckGroup')
    Assignment = apps.get_model('smart_meter', 'MeterCheckGroupAuditAssignment')
    Assignment.objects.bulk_create([
        Assignment(group_id=group.pk, meter_id=group.check_meter_id, start_date=date(1900, 1, 1))
        for group in Group.objects.all().iterator()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_unit_iesco_bill_active'),
        ('smart_meter', '0045_connection_event_capture_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='metercheckgroup',
            name='automatic_coverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metercheckgroup',
            name='coverage_mode',
            field=models.CharField(choices=[('property', 'All units in property'), ('units', 'Selected units')], default='property', max_length=10),
        ),
        migrations.AddField(
            model_name='metercheckgroup',
            name='coverage_units',
            field=models.ManyToManyField(blank=True, related_name='automatic_check_groups', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='metercheckgroupmembership',
            name='assigned_automatically',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MeterCheckGroupAuditAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Exclusive end date', null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_assignments', to='smart_meter.metercheckgroup')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_group_audit_assignments', to='smart_meter.meter')),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.RunPython(seed_audit_assignments, migrations.RunPython.noop),
    ]
