# Generated by Django 5.2.4 on 2025-07-08 09:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('easypaisa', 'Easy_Paisa'), ('bank_transfer', 'Bank Transfer')], default='bank_transfer', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('receipt_sent_via', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Both'), ('none', 'Not Sent')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leases.lease')),
            ],
        ),
    ]
