# Generated by Django 5.2.4 on 2025-12-17 22:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentmethod'),
        ('leases', '0026_lease_agreement_charges_lease_internet_charges_and_more'),
        ('payments', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('LEASE', 'Lease Payment'), ('SECURITY', 'Security Deposit'), ('SPLIT', 'Split (Lease + Security)')], default='LEASE', max_length=20)),
                ('total_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lease_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('security_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('security_type', models.CharField(blank=True, choices=[('PAYMENT', 'Payment In'), ('REFUND', 'Refund Out'), ('DAMAGE', 'Damage / Adjustment'), ('ADJUST', 'Manual Adjustment')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='leases.lease')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.paymentmethod')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='allocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_payment', to='payments.paymentallocation'),
        ),
    ]
