# Generated by Django 5.2.4 on 2025-12-19 21:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentallocation_payment_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='total_received',
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='last_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='lease_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='security_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='security_type',
            field=models.CharField(blank=True, choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('DAMAGE', 'Damage'), ('ADJUST', 'Adjust')], default='PAYMENT', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AllocationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_data', models.JSONField()),
                ('new_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.paymentallocation')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
