# Generated by Django 5.2.4 on 2026-08-15 14:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_allocation_relations_to_payment_detail'),
        ('smart_meter', '0019_meter_credit_control_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='electricity_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Part of the lease amount explicitly allocated to electricity.', max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='electricity_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electricity_payment_details', to='smart_meter.meter'),
        ),
    ]
