# Generated by Django 5.2.4 on 2025-08-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Tenant Management System', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=25)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_user', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=512)),
                ('whatsapp_number', models.CharField(blank=True, max_length=40)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=128)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=128)),
                ('twilio_from_number', models.CharField(blank=True, max_length=40)),
                ('currency_code', models.CharField(default='PKR', max_length=8)),
                ('unit_rate_per_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('service_charge_flat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('listener_host', models.CharField(default='127.0.0.1', max_length=100)),
                ('listener_port', models.PositiveIntegerField(default=6000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
