# Generated by Django 5.2.4 on 2025-10-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='country_code',
            field=models.CharField(default='+92', max_length=4),
        ),
    ]
