# Generated by Django 5.2.4 on 2025-10-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalsettings_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='time_zone',
            field=models.CharField(default='Asia/Karachi', max_length=64),
        ),
    ]
