# Generated by Django 5.2.4 on 2025-12-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globalsettings_time_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Internal code, e.g. 'cash', 'easypaisa', 'bank_transfer'", unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Cash', 'Easy Paisa', 'Bank Transfer'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this method from new payments, while keeping old payments intact.')),
                ('sort_order', models.PositiveIntegerField(default=10, help_text='Lower numbers show first in dropdowns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
