# Generated by Django 5.2.4 on 2026-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='billing_cap_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional invoice cap. Use 0 for no cap.', max_digits=10),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_grace_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_type',
            field=models.CharField(choices=[('fixed', 'Fixed amount'), ('percent', 'Percentage')], default='fixed', max_length=10),
        ),
    ]
