# Generated by Django 5.2.4 on 2026-05-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_globalsettings_billing_cap_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='enable_debug_toolbar',
            field=models.BooleanField(default=False),
        ),
    ]
