# Generated by Django 5.2.4 on 2026-06-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_globalsettings_lease_file_share_valid_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_enabled',
            field=models.BooleanField(default=True, help_text='Enable automated tenant assistant replies for inbound WhatsApp messages.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_model',
            field=models.CharField(default='gpt-4o-mini', help_text='OpenAI model used for WhatsApp AI tasks. Keep API keys in .env, not here.', max_length=80),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_ocr_provider',
            field=models.CharField(choices=[('basic', 'Basic'), ('openai', 'OpenAI Vision')], default='basic', help_text='Basic stores media for admin review. OpenAI Vision extracts receipt text when OPENAI_API_KEY is configured.', max_length=30),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_provider',
            field=models.CharField(choices=[('rules', 'Rules only'), ('openai', 'OpenAI')], default='rules', help_text='Rules only uses local matching. OpenAI enables AI OCR/understanding when OPENAI_API_KEY is configured.', max_length=30),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_use_celery',
            field=models.BooleanField(default=False, help_text='Queue WhatsApp AI work through Celery when a worker is running; otherwise TMS uses a local background thread.'),
        ),
    ]
