# Generated by Django 5.2.4 on 2026-06-29 04:37

from django.db import migrations, models


def enable_openai_whatsapp_ai(apps, schema_editor):
    GlobalSettings = apps.get_model("core", "GlobalSettings")
    GlobalSettings.objects.update(
        whatsapp_ai_enabled=True,
        whatsapp_ai_provider="openai",
        whatsapp_ai_ocr_provider="openai",
    )


def restore_basic_whatsapp_ai(apps, schema_editor):
    GlobalSettings = apps.get_model("core", "GlobalSettings")
    GlobalSettings.objects.update(
        whatsapp_ai_provider="rules",
        whatsapp_ai_ocr_provider="basic",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_whatsapp_ai_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='whatsapp_ai_ocr_provider',
            field=models.CharField(choices=[('basic', 'Basic'), ('openai', 'OpenAI Vision')], default='openai', help_text='Basic stores media for admin review. OpenAI Vision extracts receipt text when OPENAI_API_KEY is configured.', max_length=30),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='whatsapp_ai_provider',
            field=models.CharField(choices=[('rules', 'Rules only'), ('openai', 'OpenAI')], default='openai', help_text='Rules only uses local matching. OpenAI enables AI OCR/understanding when OPENAI_API_KEY is configured.', max_length=30),
        ),
        migrations.RunPython(enable_openai_whatsapp_ai, restore_basic_whatsapp_ai),
    ]
