# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_default_whatsapp_ai_openai"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="whatsapp_media_retention_days",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Days to keep downloaded WhatsApp media files. Raw webhook logs are not deleted.",
            ),
        ),
    ]
