# Generated by Django 5.2.4 on 2026-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_globalsettings_whatsapp_media_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_auto_apply',
            field=models.BooleanField(default=True, help_text='If off, reminder-based late fees wait for approval before being added to invoices.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_auto_send_reminders',
            field=models.BooleanField(default=False, help_text='If on, the scheduled late fee job sends WhatsApp reminders automatically.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_max_reminders',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited. Reminders and reminder-based fees stop once this count is reached.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_reminder_interval_days',
            field=models.PositiveIntegerField(default=5, help_text='Days between each late fee reminder after the grace period.'),
        ),
    ]
