# Generated by Django 5.2.4 on 2026-07-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_globalsettings_late_fee_auto_apply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_assignment_default_status',
            field=models.CharField(default='assigned', help_text='Status used when staff assigns a handyman and no status is selected.', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_enable_ratings',
            field=models.BooleanField(default=True, help_text='Show and accept tenant ratings for handyman jobs.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_enable_whatsapp_job_uploads',
            field=models.BooleanField(default=True, help_text='Allow handymen to upload invoices and job photos from WhatsApp.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_enable_whatsapp_profile_updates',
            field=models.BooleanField(default=True, help_text='Allow handymen to update profile photo and ID card images from WhatsApp.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_id_back_command',
            field=models.CharField(default='ID BACK', help_text='WhatsApp command for updating the back ID card image.', max_length=40),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_id_front_command',
            field=models.CharField(default='ID FRONT', help_text='WhatsApp command for updating the front ID card image.', max_length=40),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_invoice_command',
            field=models.CharField(default='INVOICE', help_text='WhatsApp command for attaching an invoice to the active job.', max_length=40),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_job_photo_command',
            field=models.CharField(default='PHOTO', help_text='WhatsApp command for attaching a job photo to the active job.', max_length=40),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_profile_photo_command',
            field=models.CharField(default='PROFILE PHOTO', help_text='WhatsApp command for updating the handyman profile photo.', max_length=40),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='handyman_require_id_documents',
            field=models.BooleanField(default=False, help_text='Require front and back ID card images before marking a handyman fully documented.'),
        ),
    ]
