# Generated by Django 5.2.4 on 2026-07-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_globalsettings_handyman_assignment_default_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='police_verification_document_category_code',
            field=models.CharField(default='police_verification', help_text='Lease document category code used to mark police verification as complete.', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='police_verification_link_valid_hours',
            field=models.PositiveIntegerField(default=48, help_text='Hours a public police verification link remains valid.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='police_verification_whatsapp_command',
            field=models.CharField(default='Police Verification', help_text='WhatsApp command tenants can send to receive the police verification link.', max_length=80),
        ),
    ]
