# Generated by Django 5.2.4 on 2026-07-13 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_globalsettings_whatsapp_pending_request_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_accounts_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_whatsapp_support_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_enable_roman_urdu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_enable_urdu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_fallback_to_rules',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_generated_responses_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_history_limit',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_mask_sensitive_fields',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_max_reply_length',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_max_tool_rounds',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_min_confidence',
            field=models.PositiveSmallIntegerField(default=65),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_multiple_tools_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_routing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_satisfaction_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_store_logs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_ai_temperature',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_allow_handover_reassignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_allow_manual_call_action',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_allow_staff_media_relay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_allow_staff_reply_relay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_default_support_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_whatsapp_support_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_escalation_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_whatsapp_support_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_future_calling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_handover_ai_summary_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_handover_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_handover_escalation_timeout_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_handover_max_reminders',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_handover_notify_multiple_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_handover_reminder_interval_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_leasing_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leasing_whatsapp_support_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_maintenance_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_whatsapp_support_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_return_to_ai_after_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_staff_reply_prefix',
            field=models.CharField(default='Management:', max_length=80),
        ),
    ]
