# Generated by Django 5.2.4 on 2026-07-13 16:02

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_globalsettings_whatsapp_accounts_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='whatsapp_number',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=40),
        ),
    ]
