# Generated by Django 5.2.4 on 2026-07-17 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_proration_interval_integer_default_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_lease_months',
            field=models.PositiveSmallIntegerField(default=11, help_text='Default agreement term used for new leases and renewals.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
