# Generated by Django 5.2.4 on 2026-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_globalsettings_default_lease_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_motorcycle_parking_rate',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Default monthly motorcycle parking rate per reserved space.', max_digits=10),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_parking_enabled',
            field=models.BooleanField(default=False, help_text='Default parking availability for properties without an override.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_unauthorized_parking_penalty',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Default penalty for each unauthorized parking violation.', max_digits=10),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='water_abuse_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Penalty per blanket/item washed without Building Maintenance permission.', max_digits=10),
        ),
    ]
