# Generated by Django 5.2.4 on 2026-07-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_globalsettings_tenant_cnic_ocr_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='tenant_income_brackets',
            field=models.TextField(default='20,000 to 40,000\n40,000 to 70,000\n70,000 to 100,000\n100,000 and more', help_text='One monthly income/salary bracket per line.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tenant_occupation_options',
            field=models.TextField(default='Salary\nBusiness\nFreelancer\nStudent\nHome Maker\nGovernment Job', help_text='One suggested occupation per line. Staff and tenants may still add a value that is not listed.'),
        ),
    ]
