# Generated by Django 5.2.4 on 2026-08-15 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_globalsettings_tenant_income_brackets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='automatic_monthly_billing',
            field=models.BooleanField(default=False, help_text='Run the shared monthly billing workflow automatically when the configured day is reached.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='monthly_billing_day',
            field=models.PositiveSmallIntegerField(default=2, help_text='Day of each month when scheduled billing becomes due (1-28).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
