# Generated by Django 5.2.4 on 2026-08-15 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_globalsettings_automatic_monthly_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='late_fee_automation_start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Batch late-fee reminders only consider invoices due on or after this date. Older overdue invoices remain available for individual review.'),
        ),
    ]
