# Generated by Django 5.2.4 on 2026-08-16 10:16

from decimal import Decimal
from django.db import migrations, models


def backfill_global_electricity_rate(apps, schema_editor):
    GlobalSettings = apps.get_model("core", "GlobalSettings")
    GlobalSettings.objects.filter(unit_rate_per_kwh=0).update(
        unit_rate_per_kwh=Decimal("50.0000")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_globalsettings_late_fee_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='unit_rate_per_kwh',
            field=models.DecimalField(decimal_places=4, default=Decimal('50.0000'), help_text='Global electricity rate. Override order: Global, Property, Unit, Meter, then Lease; the last nonblank value wins.', max_digits=10),
        ),
        migrations.RunPython(
            backfill_global_electricity_rate,
            migrations.RunPython.noop,
        ),
    ]
