# Generated by Django 5.2.4 on 2026-08-16 11:29

from django.db import migrations, models


DEFAULT_INCOME_BRACKETS = (
    "20,000 to 40,000",
    "40,000 to 70,000",
    "70,000 to 100,000",
    "100,000 and more",
)
DEFAULT_OCCUPATIONS = (
    "Salary",
    "Business",
    "Freelancer",
    "Student",
    "Home Maker",
    "Government Job",
)


def _lines(value):
    return list(dict.fromkeys(
        line.strip() for line in str(value or "").splitlines() if line.strip()
    ))


def seed_tenant_reference_options(apps, schema_editor):
    GlobalSettings = apps.get_model("core", "GlobalSettings")
    TenantIncomeBracket = apps.get_model("core", "TenantIncomeBracket")
    TenantOccupationOption = apps.get_model("core", "TenantOccupationOption")
    settings_obj = GlobalSettings.objects.filter(pk=1).first()
    income_values = _lines(getattr(settings_obj, "tenant_income_brackets", "")) or list(DEFAULT_INCOME_BRACKETS)
    occupation_values = _lines(getattr(settings_obj, "tenant_occupation_options", "")) or list(DEFAULT_OCCUPATIONS)
    for index, name in enumerate(income_values, start=1):
        TenantIncomeBracket.objects.update_or_create(
            name=name,
            defaults={"sort_order": index * 10, "is_active": True},
        )
    for index, name in enumerate(occupation_values, start=1):
        TenantOccupationOption.objects.update_or_create(
            name=name,
            defaults={"sort_order": index * 10, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_globalsettings_unit_rate_per_kwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantIncomeBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant income bracket',
                'verbose_name_plural': 'Tenant income brackets',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantOccupationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant occupation option',
                'verbose_name_plural': 'Tenant occupation options',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.RunPython(
            seed_tenant_reference_options,
            migrations.RunPython.noop,
        ),
    ]
