# Generated by Django 5.2.4 on 2025-08-17 23:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_default_category(apps, schema_editor):
    ItemCategory = apps.get_model('invoices', 'ItemCategory')
    InvoiceItem = apps.get_model('invoices', 'InvoiceItem')

    # Ensure we have at least one category and backfill
    cat, _ = ItemCategory.objects.get_or_create(
        name='Rent',
        defaults={'is_active': True},
    )
    InvoiceItem.objects.filter(
        category__isnull=True).update(category_id=cat.id)


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('leases', '0013_remove_lease_water_meter_reading_and_more'),
    ]

    operations = [
        # ItemCategory: STATE ONLY (table already exists in DB)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ItemCategory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True,
                         primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=80, unique=True)),
                        ('is_active', models.BooleanField(default=True)),
                    ],
                    options={'ordering': ['name']},
                ),
            ],
            database_operations=[],
        ),

        # tax_rate: STATE ONLY removal (column already gone in DB)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='invoiceitem',
                    name='tax_rate',
                ),
            ],
            database_operations=[],
        ),

        # Add category FK as nullable, then backfill, then make NOT NULL
        migrations.AddField(
            model_name='invoiceitem',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='invoices.itemcategory',
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(seed_default_category, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoiceitem',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='invoices.itemcategory',
                null=False,
                blank=False,
            ),
        ),

        # RecurringCharge as you had it
        migrations.CreateModel(
            name='RecurringCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10,
                                               validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='invoices.itemcategory')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='recurring_charges', to='leases.lease')),
            ],
            options={'ordering': ['lease_id', 'category__name']},
        ),
    ]
