# Generated by Django 5.2.4 on 2025-08-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_migrate_chargetype_to_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargeType',
        ),
    ]
