# Generated by Django 5.2.4 on 2025-08-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_delete_chargetype'),
        ('leases', '0015_leasefamily_delete_leasefamilymember'),
        ('properties', '0011_unit_is_smart_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Use first day of month, e.g. 2025-09-01')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('posted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recurringcharge',
            options={},
        ),
        migrations.RemoveField(
            model_name='recurringcharge',
            name='created_at',
        ),
        migrations.AddField(
            model_name='recurringcharge',
            name='combine_with_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurringcharge',
            name='kind',
            field=models.CharField(choices=[('FIXED', 'Fixed amount'), ('WATER_SPLIT', 'Water split (per property)')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='recurringcharge',
            name='last_applied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringcharge',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='recurringcharge',
            name='scope',
            field=models.CharField(choices=[('LEASE', 'One lease'), ('PROPERTY', 'All active leases in a property'), ('GLOBAL', 'All active leases')], default='LEASE', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringcharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recurringcharge',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leases.lease'),
        ),
        migrations.AddIndex(
            model_name='recurringcharge',
            index=models.Index(fields=['active', 'scope', 'kind', 'start_date'], name='invoices_re_active_6987f2_idx'),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='waterbill',
            unique_together={('property', 'period')},
        ),
    ]
