# Generated by Django 5.2.4 on 2025-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_waterbill_alter_recurringcharge_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
