# Generated by Django 5.2.4 on 2025-11-13 20:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoice_amount_alter_invoiceitem_amount'),
        ('leases', '0024_alter_leasemedia_file_alter_leasemedia_thumbnail'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('REQUIRED', 'Required (Agreed Deposit)'), ('PAYMENT', 'Payment In'), ('REFUND', 'Refund Out'), ('DAMAGE', 'Damage / Adjustment'), ('ADJUST', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_deposit_movements', to='invoices.invoiceitem')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_transactions', to='leases.lease')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_deposit_movements', to='payments.payment')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
