# Generated by Django 5.2.4 on 2025-12-17 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_securitydeposittransaction'),
        ('payments', '0004_paymentallocation_payment_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydeposittransaction',
            name='allocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_amt', to='payments.paymentallocation'),
        ),
    ]
