# Generated by Django 5.2.4 on 2026-05-17 06:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_globalsettings_billing_cap_amount_and_more'),
        ('invoices', '0013_securitydeposittransaction_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydeposittransaction',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='securitydeposittransaction',
            name='deduction_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitydeposittransaction',
            name='refund_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitydeposittransaction',
            name='refund_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_refunds', to='core.paymentmethod'),
        ),
        migrations.AddField(
            model_name='securitydeposittransaction',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
    ]
