# Generated by Django 5.2.4 on 2026-06-29 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_monthly_billing_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybillingrun',
            name='audit_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monthlybillingrun',
            name='created_invoice_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monthlybillingrun',
            name='dry_run_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlybillingrun',
            name='excluded_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlybillingrun',
            name='manual_electric_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlybillingrun',
            name='pdf_generating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlybillingrun',
            name='rolled_back_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlybillingrun',
            name='sending_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='created_invoice_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='created_invoice_item_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='dry_run_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='electric_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='electric_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='excluded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excluded_monthly_billing_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='excluded_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='manual_electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='rollback_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monthlybillingrunitem',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybillingrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('preflight', 'Preflight'), ('generating', 'Generating'), ('ready', 'Ready'), ('partial', 'Partial'), ('sent', 'Sent'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlybillingrunitem',
            name='issue_code',
            field=models.CharField(blank=True, choices=[('inactive_lease', 'Inactive lease'), ('missing_recurring_invoice_setup', 'Missing recurring invoice setup'), ('recurring_invoice_generation_failed', 'Recurring invoice generation failed'), ('duplicate_invoice_exists', 'Duplicate invoice exists'), ('latest_meter_reading_missing', 'Latest meter reading missing'), ('meter_offline', 'Meter offline'), ('manual_electric_billing', 'Manual electric billing'), ('electric_billing_not_verified', 'Electric billing not verified'), ('water_charge_missing', 'Water charge missing'), ('tenant_phone_missing', 'Tenant phone missing'), ('pdf_generation_failed', 'PDF generation failed'), ('whatsapp_send_failed', 'WhatsApp send failed'), ('unusual_invoice_total', 'Unusual invoice total'), ('zero_invoice_total', 'Zero invoice total')], max_length=80),
        ),
        migrations.AlterField(
            model_name='monthlybillingrunitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_send', 'Ready to Send'), ('pending_attention', 'Pending Attention'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('excluded', 'Excluded'), ('rolled_back', 'Rolled Back')], default='draft', max_length=30),
        ),
    ]
