# Generated by Django 5.2.4 on 2026-06-29 13:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_monthlybillingrun_audit_log_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProgressJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('run_billing', 'Run Billing'), ('preflight', 'Preflight'), ('generate_recurring', 'Generate Recurring'), ('generate_electric', 'Generate Electric'), ('prepare_ready', 'Prepare Ready'), ('generate_pdfs', 'Generate PDFs'), ('send_ready', 'Send WhatsApp'), ('retry_failed', 'Retry Failed'), ('rollback_run', 'Rollback Run')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('rq_job_id', models.CharField(blank=True, max_length=120)),
                ('current_step', models.CharField(blank=True, max_length=120)),
                ('current_tenant', models.CharField(blank=True, max_length=160)),
                ('current_property', models.CharField(blank=True, max_length=160)),
                ('current_unit', models.CharField(blank=True, max_length=80)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('average_seconds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_remaining_seconds', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error_text', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_jobs', to='invoices.monthlybillingrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_progress_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['billing_run', 'status'], name='invoices_bi_billing_ca7b85_idx'), models.Index(fields=['rq_job_id'], name='invoices_bi_rq_job__54195f_idx')],
            },
        ),
    ]
