# Generated by Django 5.2.4 on 2026-07-01 15:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_billingprogressjob'),
        ('whatsapp', '0009_alter_whatsapputilitytemplate_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLateFeeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_number', models.PositiveIntegerField()),
                ('sent_via', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Reminder sent'), ('fee_pending', 'Fee pending approval'), ('fee_applied', 'Fee applied'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_reminders', to='invoices.invoice')),
                ('late_fee_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.invoiceitem')),
                ('whatsapp_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_fee_reminders', to='whatsapp.whatsappmessagelog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'reminder_number'], name='invoices_in_invoice_540424_idx'), models.Index(fields=['status'], name='invoices_in_status_7220e8_idx')],
            },
        ),
    ]
