# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0018_invoicelatefeereminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
