# Generated by Django 5.2.4 on 2026-08-15 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_security_deposit_ledger_transfer'),
        ('whatsapp', '0019_alter_pendingwhatsappmedia_target_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoicelatefeereminder',
            constraint=models.UniqueConstraint(fields=('invoice', 'reminder_number'), name='uniq_invoice_late_fee_reminder_number'),
        ),
        migrations.AddConstraint(
            model_name='monthlybillingrun',
            constraint=models.UniqueConstraint(fields=('billing_month',), name='uniq_monthly_billing_run_month'),
        ),
    ]
