# Generated by Django 5.2.4 on 2026-09-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_invoice_late_fee_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='IescoBillReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=20)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('consumer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('consumer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('tariff_category', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_month', models.CharField(max_length=20)),
                ('reading_date', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_date', models.CharField(blank=True, max_length=20, null=True)),
                ('due_date', models.CharField(blank=True, max_length=20, null=True)),
                ('grand_total', models.CharField(blank=True, max_length=30, null=True)),
                ('bill_history', models.JSONField(blank=True, default=list)),
                ('current_month_paid', models.BooleanField(blank=True, help_text='Paid status of the most recent completed month in PITC bill history.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='iescobillreading',
            constraint=models.UniqueConstraint(fields=('reference_no', 'bill_month'), name='uniq_iesco_reference_bill_month'),
        ),
    ]
