# Generated by Django 5.2.4 on 2026-09-08 14:53

import django.core.validators
import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_iescostandalonemeter_iescobillreading_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iescobillreading',
            name='bill_pdf',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.iesco_bill_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='iescobillreading',
            name='pdf_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
