# Generated by Django 5.2.4 on 2026-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0031_iescobillreading_bill_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iescobillreading',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='iescobillreading',
            name='meter_readings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='iescobillreading',
            name='meter_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='iescobillreading',
            name='payment_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='iescobillreading',
            name='current_month_paid',
            field=models.BooleanField(blank=True, help_text='Paid status of the currently displayed PITC bill.', null=True),
        ),
    ]
