# Generated by Django 5.2.4 on 2026-09-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_iesco_meter_registers_and_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='iescobillreading',
            name='arrears',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='iescobillreading',
            name='current_bill',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
