# Generated by Django 5.2.4 on 2026-09-09 08:18

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_iesco_current_bill_and_arrears'),
    ]

    operations = [
        migrations.AddField(
            model_name='iescobillreading',
            name='reminder_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='iescobillreading',
            name='reminder_phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='iescobillreading',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iescostandalonemeter',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, help_text='WhatsApp reminder number when this meter is not assigned to a unit.', max_length=32, null=True),
        ),
    ]
