# Generated by Django 5.2.4 on 2026-09-16 08:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0035_iesco_reconciliation_trust'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IescoHelperDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('paired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('helper_version', models.CharField(blank=True, max_length=32)),
                ('paired_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iesco_helper_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IescoHelperPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paired', 'Paired'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairings', to='invoices.iescohelperdevice')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iesco_helper_pairings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
