"""
Django settings for tms project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util
import logging
import os
from pathlib import Path

from dotenv import load_dotenv
from easy_thumbnails.conf import Settings as thumb_settings

LOG_DIR = r"C:\tenant_management_system\logs"
os.makedirs(LOG_DIR, exist_ok=True)
# import pymysql
# pymysql.install_as_MySQLdb()

AUTH_USER_MODEL = "accounts.Account"

# turn off if you don’t want any deduction yet
METER_ENABLE_BALANCE_DEDUCTION = True
METER_ENABLE_PREPAID_CUTOFF = False  # keep False until prepaid is live

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env", override=True)
APPEND_SLASH = True  # or False if you prefer

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-jlxkrq^@ftkp%$ej3eoo91*%130d@x(5t9q=4g+@i-)8i^r#jt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*",
    "0.0.0.0",
    "localhost",
    "192.168.100.39",
    "192.168.100.28",
    "119.156.230.185",
    "desktop-004",
    "kirayas.com",
    "www.kirayas.com",
]


CSRF_TRUSTED_ORIGINS = [
    "http://119.156.230.185",
    "http://192.168.100.39",
    "http://192.168.100.28",
    "https://kirayas.com",
    "https://www.kirayas.com",
]

PUBLIC_BASE_URL = (
    os.getenv("PUBLIC_BASE_URL", "https://kirayas.com").strip().rstrip("/")
    or "https://kirayas.com"
)


INSTALLED_APPS = [
    "marketing.apps.MarketingConfig",
    "dashboard",
    "accounts.apps.AccountsConfig",
    "properties.apps.PropertiesConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "core.apps.CoreConfig",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tenants",
    "expenses",
    "documents",
    "smart_meter",
    "notifications.apps.NotificationsConfig",
    "django_select2",
    "leases.apps.LeasesConfig",
    "reports",
    "invoices.apps.InvoicesConfig",
    "crispy_forms",
    "crispy_bootstrap5",
    "django.contrib.humanize",
    "django_tables2",
    "reportlab",
    "utilities",
    "rest_framework",
    "payments",
    "dal",
    "weasyprint",
    "dal_select2",
    "maintenance",
    "handyman.apps.HandymanConfig",
    "whatsapp.apps.WhatsappConfig",
    "django_extensions",
    "django_filters",
    "widget_tweaks",
    "imagekit",
    "django_ckeditor_5",
    # Third-party apps
]

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "|",
            "link",
            "bulletedList",
            "numberedList",
            "|",
            "undo",
            "redo",
        ],
        "language": "en",
    },
}

WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "1186798447852753")
WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv(
    "WHATSAPP_BUSINESS_ACCOUNT_ID", "4573255446332475"
)
WHATSAPP_VERIFY_TOKEN = os.getenv("WHATSAPP_VERIFY_TOKEN", "TMS_WHATSAPP_VERIFY_2026")
WHATSAPP_APP_SECRET = os.getenv(
    "WHATSAPP_APP_SECRET",
    "",
).strip()
WHATSAPP_API_VERSION = os.getenv("WHATSAPP_API_VERSION", "v23.0")
WHATSAPP_DEFAULT_COUNTRY_CODE = os.getenv("WHATSAPP_DEFAULT_COUNTRY_CODE", "+92")
WHATSAPP_REQUEST_TIMEOUT = int(os.getenv("WHATSAPP_REQUEST_TIMEOUT", "20"))


def _whatsapp_positive_int_setting(name, default):
    try:
        value = int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        value = default
    if value <= 0:
        logging.getLogger(__name__).warning(
            "Invalid %s configured; using %s.", name, default
        )
        value = default
    return value


WHATSAPP_MAX_INBOUND_MEDIA_BYTES = _whatsapp_positive_int_setting(
    "WHATSAPP_MAX_INBOUND_MEDIA_BYTES",
    16 * 1024 * 1024,
)
WHATSAPP_MAX_INBOUND_VIDEO_BYTES = _whatsapp_positive_int_setting(
    "WHATSAPP_MAX_INBOUND_VIDEO_BYTES",
    250 * 1024 * 1024,
)
WHATSAPP_DEFAULT_TEMPLATE_NAME = os.getenv(
    "WHATSAPP_DEFAULT_TEMPLATE_NAME", "hello_world"
)
WHATSAPP_DEFAULT_TEMPLATE_LANGUAGE = os.getenv(
    "WHATSAPP_DEFAULT_TEMPLATE_LANGUAGE", "en"
)
WHATSAPP_DEFAULT_LANGUAGE = os.getenv("WHATSAPP_DEFAULT_LANGUAGE", "en")
WHATSAPP_AI_ENABLED = os.getenv("WHATSAPP_AI_ENABLED", "true").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
WHATSAPP_AI_PROVIDER = os.getenv("WHATSAPP_AI_PROVIDER", "rules")
WHATSAPP_AI_OCR_PROVIDER = os.getenv("WHATSAPP_AI_OCR_PROVIDER", "basic")
WHATSAPP_AI_OCR_IMAGE_DETAIL = os.getenv(
    "WHATSAPP_AI_OCR_IMAGE_DETAIL",
    "low",
).strip().lower()
if WHATSAPP_AI_OCR_IMAGE_DETAIL not in {"low", "high", "auto"}:
    logging.getLogger(__name__).warning(
        "Invalid WHATSAPP_AI_OCR_IMAGE_DETAIL configured; using low."
    )
    WHATSAPP_AI_OCR_IMAGE_DETAIL = "low"
WHATSAPP_AI_OCR_HIGH_DETAIL_FALLBACK = os.getenv(
    "WHATSAPP_AI_OCR_HIGH_DETAIL_FALLBACK",
    "true",
).strip().lower() in {"1", "true", "yes", "on"}


def _whatsapp_ocr_positive_int(name, default, minimum):
    try:
        value = int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        value = default
    if value < minimum:
        logging.getLogger(__name__).warning("Invalid %s configured; using %s.", name, default)
        value = default
    return value


WHATSAPP_AI_OCR_MAX_IMAGE_DIMENSION = _whatsapp_ocr_positive_int(
    "WHATSAPP_AI_OCR_MAX_IMAGE_DIMENSION", 1600, 256
)
WHATSAPP_AI_OCR_MAX_OUTPUT_TOKENS = _whatsapp_ocr_positive_int(
    "WHATSAPP_AI_OCR_MAX_OUTPUT_TOKENS", 300, 100
)
WHATSAPP_AI_USE_CELERY = os.getenv("WHATSAPP_AI_USE_CELERY", "false").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
WHATSAPP_PUBLIC_BASE_URL = os.getenv(
    "WHATSAPP_PUBLIC_BASE_URL", PUBLIC_BASE_URL
).rstrip("/")
WHATSAPP_MODE_SESSION_MINUTES = int(os.getenv("WHATSAPP_MODE_SESSION_MINUTES", "60"))
WHATSAPP_ROLE_GROUP_NAMES = [
    "Guest",
    "Tenant",
    "Staff",
    "Billing Staff",
    "Property Manager",
    "Administrator",
]
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_WHATSAPP_AI_MODEL = os.getenv("OPENAI_WHATSAPP_AI_MODEL", "gpt-4o-mini")


INSTALLED_APPS += ["easy_thumbnails", "image_cropping"]
THUMBNAIL_PROCESSORS = (
    "image_cropping.thumbnail_processors.crop_corners",
) + thumb_settings.THUMBNAIL_PROCESSORS
IMAGE_CROPPING_THUMB_SIZE = (300, 300)

DEBUG_TOOLBAR_INSTALLED = importlib.util.find_spec("debug_toolbar") is not None
IS_LOCAL_DEVELOPMENT = (
    os.getenv("TMS_LOCAL_DEV", "").lower()
    in {
        "1",
        "true",
        "yes",
        "on",
    }
    or os.name == "nt"
)
ENABLE_LOCAL_DEBUG_TOOLBAR = (
    DEBUG
    and IS_LOCAL_DEVELOPMENT
    and DEBUG_TOOLBAR_INSTALLED
    and os.getenv("TMS_DISABLE_DEBUG_TOOLBAR", "").lower()
    not in {
        "1",
        "true",
        "yes",
        "on",
    }
)

if ENABLE_LOCAL_DEBUG_TOOLBAR:
    INSTALLED_APPS += ["debug_toolbar"]

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "marketing.middleware.MarketingHostMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.ImpersonationMiddleware",
    "accounts.middleware.NoCacheAuthenticatedMiddleware",
    "accounts.middleware.PermissionEnforcementMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "notifications.middleware.NotificationRecursionMiddleware",  # Add this line
]

if ENABLE_LOCAL_DEBUG_TOOLBAR:
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.contrib.auth.middleware.AuthenticationMiddleware") + 1,
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    )

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}
ROOT_URLCONF = "tms.urls"

INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
    "::1",
    "192.168.0.0/16",
]

DEBUG_TOOLBAR_CONFIG = {
    "INTERCEPT_REDIRECTS": False,
    "SHOW_TOOLBAR_CALLBACK": "core.debug_toolbar.show_toolbar",
    "DISABLE_PANELS": {
        "debug_toolbar.panels.profiling.ProfilingPanel",
        "debug_toolbar.panels.redirects.RedirectsPanel",
    },
}

LEASE_STAMP_SCALE = 0.5  # overall scale
LEASE_STAMP_PROP_SCALE = 0.52
LEASE_STAMP_TS_SCALE = 0.48
LEASE_STAMP_DESC_SCALE = 0.46
LEASE_STAMP_MIN_PX = 11
LEASE_STAMP_FONT = r"C:\Windows\Fonts\arial.ttf"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.global_settings",
            ],
            "debug": True,  # <-- add this line here
        },
    },
]

WSGI_APPLICATION = "tms.wsgi.application"

CSRF_FAILURE_VIEW = "tenants.csrf.csrf_failure"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "tenant_management",
        "USER": "user",
        "PASSWORD": "abcd7861",
        "HOST": "localhost",
        "PORT": "6604",
        "init_command": "SET time_zone = '+00:00'",
        "CONN_MAX_AGE": 60,  # keep connections up to 60s (or 0 to open per request)
        "CONN_HEALTH_CHECKS": True,  # ping before using a persistent connection
    }
}

# Local test fallback when MySQL test-database creation is unavailable.
# Production remains on MySQL unless this explicit switch is enabled.
if os.getenv("TMS_TEST_SQLITE", "").strip().lower() in {"1", "true", "yes", "on"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / ".codex_tmp" / "tms_tests.sqlite3",
        }
    }

SOCKET_SERVER_HOST = "0.0.0.0"
SOCKET_SERVER_PORT = 6000

TEMPLATES[0]["OPTIONS"]["builtins"] = [
    "django.contrib.humanize.templatetags.humanize",
    "core.templatetags.money_tags",
]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # "bootstrap4" if on BS4
CRISPY_TEMPLATE_PACK = "bootstrap5"  # match your Bootstrap version
# settings.py
CONTROL_LISTENER_HOST = "127.0.0.1"  # or IP/hostname of your forwarder
CONTROL_LISTENER_PORT = 7000  # whatever your forwarder listens on

# tms/settings.py

# Celery Configuration
CELERY_BROKER_URL = "redis://localhost:6379/0"  # Using Redis as the broker
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"  # Storing results in Redis

# Local RQ queue for monthly billing background jobs.
BILLING_RQ_REDIS_URL = os.getenv("BILLING_RQ_REDIS_URL", "redis://localhost:6379/1")
BILLING_RQ_QUEUE = os.getenv("BILLING_RQ_QUEUE", "billing")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

DISABLE_CUTOFFS = False

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Karachi"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# -----------------------------
# Static / Media (Local + Production Safe)
# -----------------------------

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = "/media/"
MEDIA_ROOT = Path(
    os.getenv(
        "MEDIA_ROOT",
        "/home/ivs/tms_media",
    )
)

import os

APP_ENVIRONMENT = (
    os.getenv(
        "APP_ENVIRONMENT",
        "production",
    )
    .strip()
    .lower()
)

APP_ENVIRONMENT_LABEL = os.getenv(
    "APP_ENVIRONMENT_LABEL",
    APP_ENVIRONMENT.upper(),
).strip()
# Optional reverse-proxy path support for legacy deployments still mounted at
# /tms/. Kirayas is served from the domain root, so no prefix is the default.
FORCE_SCRIPT_NAME = os.getenv("FORCE_SCRIPT_NAME") or None
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-mail.outlook.com')
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', True)
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'your-email@gmail.com')
# EMAIL_HOST_PASSWORD = os.getenv(
#    'EMAIL_HOST_PASSWORD', 'your-email-password')

# Email settings for Outlook
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = 'smtp.office365.com'  # For Microsoft 365/Outlook
EMAIL_HOST = "smtp.freesmtpservers.com"  # Alternative (for Outlook.com)
EMAIL_PORT = 25
EMAIL_USE_TLS = True  # Must be True (not SSL)
EMAIL_HOST_USER = "issasohail@gmail.com"  # Your Outlook email
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")  # From .env
DEFAULT_FROM_EMAIL = "issasohail@gmail.com"  # Same as EMAIL_HOST_USER

# SMS settings
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
}

LOGIN_URL = os.getenv("LOGIN_URL", "/accounts/login/")
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "login"

# Public Kirayas website. The contact destination may be set independently;
# when empty, the existing GlobalSettings.whatsapp_number is used.
MARKETING_PUBLIC_HOST = os.getenv("MARKETING_PUBLIC_HOST", "kirayas.com").strip().lower()
MARKETING_PUBLIC_BASE_URL = os.getenv(
    "MARKETING_PUBLIC_BASE_URL", "https://kirayas.com"
).rstrip("/")
TMS_PUBLIC_BASE_URL = os.getenv(
    "TMS_PUBLIC_BASE_URL", PUBLIC_BASE_URL
).rstrip("/")
MARKETING_WHATSAPP_NUMBER = os.getenv("MARKETING_WHATSAPP_NUMBER", "").strip()

# Settings embeds several same-site management pages in inline panels.
# Keep clickjacking protection for other sites while allowing our own pages.
X_FRAME_OPTIONS = "SAMEORIGIN"

WEASYPRINT_BASEURL = "http://localhost:8001"
WEASYPRINT_DPI = 300

EMAIL_DEBUG = True
# --- logging ---
LOG_DIR = r"C:\tenant_management_system\logs"
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,  # REQUIRED
    "disable_existing_loggers": False,
    "formatters": {
        "brief": {"format": "%(levelname)s %(message)s"},
        "audit": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
    },
    "filters": {
        "redact_registration_tokens": {
            "()": "core.logging_filters.RedactRegistrationTokenFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "brief",
            "filters": ["redact_registration_tokens"],
        },
        "meter_control_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "meter_control.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "audit",
        },
        "meter_listener_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "meter_listener.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "audit",
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        # UI actions (buttons, bulk, lab, meter_switch)
        "meter_control": {
            "handlers": ["meter_control_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        # Listener service (CONTROL_REQUEST / TX_TO_METER etc.)
        "meter_listener": {
            "handlers": ["meter_listener_file", "console"],
            "level": "INFO",  # set to "DEBUG" to see extra detail
            "propagate": False,
        },
    },
}


if os.getenv("MEDIA_URL"):
    MEDIA_URL = os.getenv("MEDIA_URL")
elif FORCE_SCRIPT_NAME and MEDIA_URL == "/media/":
    MEDIA_URL = f"{FORCE_SCRIPT_NAME.rstrip('/')}/media/"
