"""
Django settings for tms project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from easy_thumbnails.conf import Settings as thumb_settings
import logging
from dotenv import load_dotenv
from pathlib import Path
import os
import os
LOG_DIR = r"C:\tenant_management_system\logs"
os.makedirs(LOG_DIR, exist_ok=True)
# import pymysql
# pymysql.install_as_MySQLdb()

# settings.py -> TEMPLATES[0]["OPTIONS"]["context_processors"]
"tms_config.context_processors.global_settings",

load_dotenv()

AUTH_USER_MODEL = "accounts.Account"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APPEND_SLASH = True  # or False if you prefer

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jlxkrq^@ftkp%$ej3eoo91*%130d@x(5t9q=4g+@i-)8i^r#jt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*", "0.0.0.0", "localhost",
                 "192.168.100.39", "119.156.230.185", "desktop-004"]


CSRF_TRUSTED_ORIGINS = [
    "http://119.156.230.185",
    "http://192.168.100.39",
]


INSTALLED_APPS = [

    'dashboard',
    "accounts.apps.AccountsConfig",
    'properties.apps.PropertiesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    "core.apps.CoreConfig",
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenants',
    'expenses',
    'documents',
    'smart_meter',
    'notifications.apps.NotificationsConfig',
    'django_select2',
    'leases.apps.LeasesConfig',
    'reports',
    'invoices.apps.InvoicesConfig',
    'crispy_forms',
    'crispy_bootstrap5',

    'django_tables2',
    'reportlab',
    'utilities',
    'rest_framework',
    'payments',
    'dal',
    'weasyprint',
    'dal_select2',
    'django.contrib.humanize',
    'django_extensions',
    'django_filters',
    'widget_tweaks',
    'imagekit',
    'django_ckeditor_5',

    # Third-party apps


]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', '|', 'link', 'bulletedList', 'numberedList', '|', 'undo', 'redo'],
        'language': 'en',
    },
}


INSTALLED_APPS += ['easy_thumbnails', 'image_cropping']
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumb_settings.THUMBNAIL_PROCESSORS
IMAGE_CROPPING_THUMB_SIZE = (300, 300)

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'notifications.middleware.NotificationRecursionMiddleware',  # Add this line

]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
ROOT_URLCONF = 'tms.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tenant_management',
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': 'localhost',
        'PORT': '6604',
        "init_command": "SET time_zone = '+00:00'"
    }
}

SOCKET_SERVER_HOST = '0.0.0.0'
SOCKET_SERVER_PORT = 6000


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # "bootstrap4" if on BS4
CRISPY_TEMPLATE_PACK = "bootstrap5"           # match your Bootstrap version
# settings.py
CONTROL_LISTENER_HOST = "127.0.0.1"  # or IP/hostname of your forwarder
CONTROL_LISTENER_PORT = 7000         # whatever your forwarder listens on

# tms/settings.py

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Using Redis as the broker
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Storing results in Redis


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Path to your global static files
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-mail.outlook.com')
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', True)
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'your-email@gmail.com')
# EMAIL_HOST_PASSWORD = os.getenv(
#    'EMAIL_HOST_PASSWORD', 'your-email-password')

# Email settings for Outlook
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.office365.com'  # For Microsoft 365/Outlook
EMAIL_HOST = 'smtp.freesmtpservers.com'  # Alternative (for Outlook.com)
EMAIL_PORT = 25
EMAIL_USE_TLS = True  # Must be True (not SSL)
EMAIL_HOST_USER = 'issasohail@gmail.com'  # Your Outlook email
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # From .env
DEFAULT_FROM_EMAIL = 'issasohail@gmail.com'  # Same as EMAIL_HOST_USER

# SMS settings
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

# File uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = "login"

WEASYPRINT_BASEURL = 'http://localhost:8000'
WEASYPRINT_DPI = 300

EMAIL_DEBUG = True
# --- logging ---
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"},
        "verbose":  {"format": "[%(levelname)s] %(asctime)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
            "filename": str(LOGS / "django.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "encoding": "utf-8",
            "delay": True,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}
