# Generated by Django 5.2.4 on 2025-09-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensereceipt'),
        ('invoices', '0011_alter_invoice_amount_alter_invoiceitem_amount'),
        ('properties', '0011_unit_is_smart_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unit'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.itemcategory'),
        ),
    ]
