# Generated by Django 5.2.4 on 2025-09-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereceipt',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
