# Generated by Django 5.2.4 on 2025-07-08 09:39

import image_cropping.fields
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, default='Rawalpindi,Pakistan', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_family_member', models.CharField(default=4, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=tenants.models.tenant_photo_upload_to)),
                ('photo_crop', image_cropping.fields.ImageRatioField('photo', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='photo crop')),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to=tenants.models.cnic_front_upload_to)),
                ('cnic_front_crop', image_cropping.fields.ImageRatioField('photo', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cnic front crop')),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to=tenants.models.cnic_back_upload_to)),
                ('cnic_back_crop', image_cropping.fields.ImageRatioField('photo', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cnic back crop')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
