# Generated by Django 5.2.4 on 2025-07-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='relation',
            field=models.CharField(blank=True, default='Mr.', max_length=10, null=True),
        ),
    ]
