# Generated by Django 5.2.4 on 2025-07-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='relation',
            field=models.CharField(blank=True, default='S/O.', max_length=10, null=True),
        ),
    ]
