# Generated by Django 5.2.4 on 2025-08-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cnic_digits',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=13, null=True, unique=True),
        ),
    ]
