# Generated by Django 5.2.4 on 2025-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_cnic_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
