# Generated by Django 5.2.4 on 2026-05-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_propertymedia_unitmedia'),
        ('tenants', '0007_tenant_phone2_tenant_phone3_alter_tenant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialTenantLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('family_size', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('visited', 'Visited'), ('not_interested', 'Not Interested'), ('converted', 'Converted')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_tenant_leads', to='properties.property')),
                ('interested_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_tenant_leads', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
