# Generated by Django 5.2.4 on 2026-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_police_verification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(blank=True, default='Pakistan', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(blank=True, default='Pakistani', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_vacant_flat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_vacant_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='permanent_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='province',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='temporary_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='working_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
