# Generated by Django 5.2.4 on 2026-06-03 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


DEFAULT_INTEREST_TYPES = [
    ("single_room_attached_bath_kitchen", "Single Room with Attached Bath and Kitchen", 10),
    ("two_room_flat", "2 Room Flat", 20),
    ("other", "Other", 100),
]


def split_name(name):
    parts = (name or "").strip().split()
    if not parts:
        return "Lead", ""
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], " ".join(parts[1:])


def seed_interest_types(apps, schema_editor):
    TenantInterestType = apps.get_model("tenants", "TenantInterestType")
    for code, name, sort_order in DEFAULT_INTEREST_TYPES:
        TenantInterestType.objects.get_or_create(
            code=code,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )


def migrate_old_leads_to_tenants(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    PotentialTenantLead = apps.get_model("tenants", "PotentialTenantLead")
    TenantInterestType = apps.get_model("tenants", "TenantInterestType")
    other_interest = TenantInterestType.objects.filter(code="other").first()

    for lead in PotentialTenantLead.objects.all().order_by("id"):
        tenant = None
        if lead.phone:
            tenant = Tenant.objects.filter(phone=lead.phone).first()
        if tenant is None and lead.whatsapp_number:
            tenant = Tenant.objects.filter(whatsapp_number=lead.whatsapp_number).first()
        if tenant is None:
            first_name, last_name = split_name(lead.name)
            tenant = Tenant.objects.create(
                first_name=first_name,
                last_name=last_name,
                email="",
                phone=lead.phone or "",
                cnic=f"LEAD{uuid.uuid4().hex[:11]}",
                cnic_digits=None,
                is_lead=True,
                lead_status=lead.status,
                whatsapp_number=lead.whatsapp_number or "",
                interested_building_id=lead.interested_building_id,
                interested_unit_id=lead.interested_unit_id,
                budget=lead.budget,
                family_size=lead.family_size,
                notes=lead.notes or "",
                source=lead.source or "",
                next_follow_up_date=lead.next_follow_up_date,
                created_at=lead.created_at,
                updated_at=lead.updated_at,
            )
        else:
            tenant.is_lead = True
            tenant.lead_status = lead.status
            tenant.whatsapp_number = lead.whatsapp_number or tenant.whatsapp_number or ""
            tenant.interested_building_id = lead.interested_building_id or tenant.interested_building_id
            tenant.interested_unit_id = lead.interested_unit_id or tenant.interested_unit_id
            tenant.budget = lead.budget if lead.budget is not None else tenant.budget
            tenant.family_size = lead.family_size if lead.family_size is not None else tenant.family_size
            tenant.source = lead.source or tenant.source or ""
            tenant.next_follow_up_date = lead.next_follow_up_date or tenant.next_follow_up_date
            if lead.notes and not tenant.notes:
                tenant.notes = lead.notes
            tenant.save()

        if other_interest:
            tenant.interested_in.add(other_interest)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_propertymedia_unitmedia'),
        ('tenants', '0010_tenant_city_tenant_country_tenant_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInterestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=50)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='family_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='interested_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_tenants', to='properties.property'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='interested_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_tenants', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('visited', 'Visited'), ('not_interested', 'Not Interested'), ('converted', 'Converted')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='source',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='interested_in',
            field=models.ManyToManyField(blank=True, related_name='tenants', to='tenants.tenantinteresttype'),
        ),
        migrations.RunPython(seed_interest_types, migrations.RunPython.noop),
        migrations.RunPython(migrate_old_leads_to_tenants, migrations.RunPython.noop),
    ]
