# Generated by Django 5.2.4 on 2026-06-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenantinteresttype_tenant_budget_tenant_family_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='family_size',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='interested_building',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='interested_unit',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_lead',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='lead_status',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='next_follow_up_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='source',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='whatsapp_number',
        ),
        migrations.DeleteModel(
            name='PotentialTenantLead',
        ),
    ]
