# Generated by Django 5.2.4 on 2026-06-03 20:13

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_remove_tenant_budget_remove_tenant_family_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantregistrationsubmission',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.registration_submission_upload_to),
        ),
        migrations.AddField(
            model_name='tenantregistrationsubmission',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.registration_submission_upload_to),
        ),
        migrations.AddField(
            model_name='tenantregistrationsubmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.registration_submission_upload_to),
        ),
    ]
