# Generated by Django 5.2.4 on 2026-06-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_employer_name_tenant_employer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='notify_vacant_flat',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='notify_vacant_room',
        ),
    ]
