# Generated by Django 5.2.4 on 2026-06-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_remove_tenant_notify_vacant_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
