# Generated by Django 5.2.4 on 2026-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
