# Generated by Django 5.2.4 on 2026-07-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_alter_tenant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='family_member_adults',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='family_member_children',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nadra_family_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
