# Generated by Django 5.2.4 on 2026-07-11 13:46

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_tenant_employer_address'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingregistrationperson',
            new_name='tenants_pen_submiss_978b47_idx',
            old_name='tenants_pen_submiss_6f4b14_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingregistrationperson',
            new_name='tenants_pen_cnic_di_2ec201_idx',
            old_name='tenants_pen_cnic_di_1e64d4_idx',
        ),
        migrations.AlterField(
            model_name='pendingregistrationperson',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.pending_registration_person_upload_to),
        ),
        migrations.AlterField(
            model_name='pendingregistrationperson',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.pending_registration_person_upload_to),
        ),
        migrations.AlterField(
            model_name='pendingregistrationperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.pending_registration_person_upload_to),
        ),
    ]
