# Generated by Django 5.2.4 on 2026-07-13 16:02

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_rename_tenants_pen_submiss_6f4b14_idx_tenants_pen_submiss_978b47_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistrationperson',
            name='cnic',
            field=core.model_fields.NormalizedCNICField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pendingregistrationperson',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cnic',
            field=core.model_fields.NormalizedCNICField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='emergency_contact_phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='employer_phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone2',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone3',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='reference_phone_1',
            field=core.model_fields.NormalizedPhoneField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='reference_phone_2',
            field=core.model_fields.NormalizedPhoneField(blank=True, default='', max_length=32),
        ),
    ]
