# Generated by Django 5.2.4 on 2026-07-14 16:35

import django.db.models.deletion
from django.db import migrations, models


def link_interest_types_to_building_types(apps, schema_editor):
    BuildingType = apps.get_model("properties", "BuildingType")
    Unit = apps.get_model("properties", "Unit")
    TenantInterestType = apps.get_model("tenants", "TenantInterestType")

    for building_type in BuildingType.objects.all().order_by("sort_order", "id"):
        interest_type = TenantInterestType.objects.filter(
            code=building_type.code
        ).first()
        if interest_type is None:
            interest_type = TenantInterestType.objects.create(
                name=building_type.name,
                code=building_type.code,
                is_active=building_type.is_active,
                sort_order=building_type.sort_order,
                inspection_incomplete_charge=building_type.inspection_incomplete_charge,
                key_card_not_returned_charge=building_type.key_card_not_returned_charge,
            )
        interest_type.building_type_id = building_type.pk
        interest_type.name = building_type.name
        interest_type.is_active = building_type.is_active
        interest_type.sort_order = building_type.sort_order
        interest_type.inspection_incomplete_charge = building_type.inspection_incomplete_charge
        interest_type.key_card_not_returned_charge = building_type.key_card_not_returned_charge
        interest_type.save()
        Unit.objects.filter(building_type_id=building_type.pk).update(
            interest_type_id=interest_type.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_backfill_unit_building_types'),
        ('tenants', '0023_tenantinteresttype_move_out_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinteresttype',
            name='building_type',
            field=models.OneToOneField(blank=True, help_text='Building Type that manages this internal lead-interest option.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interest_type', to='properties.buildingtype'),
        ),
        migrations.RunPython(
            link_interest_types_to_building_types,
            migrations.RunPython.noop,
        ),
    ]
