# Generated by Django 5.2.4 on 2026-07-21 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0091_first_legal_page_standard_top_margin'),
        ('tenants', '0024_link_interest_to_building_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantregistrationsubmission',
            name='created_lease',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_submission', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='tenantregistrationsubmission',
            name='field_decisions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tenantregistrationsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_information', 'Needs Information'), ('ready_for_approval', 'Ready for Approval'), ('processing', 'Processing'), ('processing_failed', 'Processing Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TenantRegistrationSubmissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(default='edit', max_length=40)),
                ('changes', models.JSONField(default=dict)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_registration_submission_edits', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='tenants.tenantregistrationsubmission')),
            ],
            options={
                'ordering': ['-edited_at', '-id'],
            },
        ),
    ]
