# Generated by Django 5.2.4 on 2026-07-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_add_missing_urdu_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='monthly_income_bracket',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Monthly Income/Salary'),
        ),
    ]
