# Generated by Django 5.2.4 on 2026-07-31 14:31

import django.db.models.deletion
import tenants.models
import tenants.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_backfill_active_lease_cnic_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRegistrationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('draft_id', models.UUIDField(db_index=True)),
                ('form_field_name', models.CharField(max_length=100)),
                ('document_kind', models.CharField(choices=[('photo', 'Photo'), ('cnic_front', 'CNIC Front'), ('cnic_back', 'CNIC Back')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('detected_content_type', models.CharField(max_length=80)),
                ('size', models.PositiveBigIntegerField()),
                ('file', models.FileField(max_length=255, storage=tenants.storage.TenantRegistrationDraftStorage(), upload_to=tenants.models.temporary_registration_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=tenants.models.temporary_registration_expiry)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_registration_uploads', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'draft_id', 'created_at'], name='tenants_tem_tenant__558b89_idx'), models.Index(fields=['expires_at'], name='tenants_tem_expires_a42dfa_idx')],
            },
        ),
    ]
