# Generated by Django 5.2.4 on 2026-07-13 16:02

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='whatsapp_number',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32),
        ),
    ]
