# Generated by Django 5.2.4 on 2025-07-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(db_column='name', max_length=100, verbose_name='Property Name')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_address', models.CharField(max_length=200)),
                ('owner_cnic', models.CharField(max_length=15)),
                ('owner_phone', models.CharField(max_length=25)),
                ('caretaker_name', models.CharField(max_length=100)),
                ('caretaker_address', models.CharField(max_length=200)),
                ('caretaker_cnic', models.CharField(max_length=15)),
                ('caretaker_phone', models.CharField(max_length=25)),
                ('property_address1', models.TextField()),
                ('property_address2', models.TextField()),
                ('property_city', models.TextField()),
                ('property_state', models.TextField()),
                ('property_zipcode', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('commercial', 'Commercial')], max_length=20)),
                ('total_units', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['property_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('electric_meter_num', models.CharField(blank=True, default='0000000000', max_length=20, null=True)),
                ('gas_meter_num', models.CharField(blank=True, default='12345', max_length=20, null=True)),
                ('society_maintenance', models.DecimalField(blank=True, decimal_places=2, default='1200.00', max_digits=10, null=True)),
                ('water_charges', models.DecimalField(blank=True, decimal_places=2, default='6000.00', max_digits=10, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default='25000.00', max_digits=10)),
                ('security_requires', models.CharField(blank=True, default='Two Months', max_length=20, null=True)),
                ('ceiling_fan', models.IntegerField(blank=True, default=3, null=True)),
                ('exhaust_fan', models.IntegerField(blank=True, default=3, null=True)),
                ('ceiling_lights', models.IntegerField(blank=True, default=16, null=True)),
                ('stove', models.IntegerField(blank=True, default=0, null=True)),
                ('keys', models.IntegerField(blank=True, default=2, null=True)),
                ('paint_condition', models.CharField(blank=True, default='New Paint with no marks or water seapage', max_length=100, null=True)),
                ('wardrobes', models.IntegerField(blank=True, default=2, null=True)),
                ('bedrooms', models.IntegerField(blank=True, default=2, null=True)),
                ('bathrooms', models.IntegerField(blank=True, default=2, null=True)),
                ('kitchens', models.IntegerField(blank=True, default=1, null=True)),
                ('hall', models.IntegerField(blank=True, default=1, null=True)),
                ('square_footage', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, default='Good Condition.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
