# Generated by Django 5.2.4 on 2025-07-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_unit_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
