# Generated by Django 5.2.4 on 2025-07-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_caretaker_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
