# Generated by Django 5.2.4 on 2025-07-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
