# Generated by Django 5.2.4 on 2025-07-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='relation',
            field=models.CharField(blank=True, default='S/O', max_length=10, null=True),
        ),
    ]
