# Generated by Django 5.2.4 on 2025-07-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='caretaker_prefix',
            field=models.CharField(blank=True, default='Mr.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_prefix',
            field=models.CharField(blank=True, default='Mr.', max_length=5, null=True),
        ),
    ]
