# Generated by Django 5.2.4 on 2025-07-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_caretaker_prefix_property_owner_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='caretaker_father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='caretaker_relation',
            field=models.CharField(blank=True, default='S/O', max_length=10, null=True),
        ),
    ]
