# Generated by Django 5.2.4 on 2025-07-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_caretaker_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_smart_meter',
            field=models.BooleanField(default=False),
        ),
    ]
