# Generated by Django 5.2.4 on 2026-05-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_unit_is_smart_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bank_account_details',
            field=models.TextField(blank=True, help_text='Default bank account/payment instructions for this property.', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bank_account_details',
            field=models.TextField(blank=True, help_text='Optional unit-specific bank account/payment instructions.', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='use_property_bank_account',
            field=models.BooleanField(default=True, help_text="Use the property's default bank account/payment instructions."),
        ),
    ]
