# Generated by Django 5.2.4 on 2026-05-17 01:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_bank_account_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=properties.models._media_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf', 'mp4', 'mov', 'avi', 'mkv'])])),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='file', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stamped_file', models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to=properties.models._media_stamped_path)),
                ('thumbnail', models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to=properties.models._media_thumbnail_path)),
                ('is_active', models.BooleanField(default=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='properties.property')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-uploaded_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=properties.models._media_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf', 'mp4', 'mov', 'avi', 'mkv'])])),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='file', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stamped_file', models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to=properties.models._media_stamped_path)),
                ('thumbnail', models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to=properties.models._media_thumbnail_path)),
                ('is_active', models.BooleanField(default=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='properties.unit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-uploaded_at'],
                'abstract': False,
            },
        ),
    ]
