# Generated by Django 5.2.4 on 2026-06-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_propertymedia_unitmedia'),
        ('tenants', '0015_remove_tenant_notify_vacant_flat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='interest_type',
            field=models.ForeignKey(blank=True, help_text='Used to match vacant units with interested tenants.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='tenants.tenantinteresttype'),
        ),
    ]
