# Generated by Django 5.2.4 on 2026-06-04 19:39

import django.core.validators
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_unit_interest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(max_length=255, upload_to=properties.models._media_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'pdf', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='unitmedia',
            name='file',
            field=models.FileField(max_length=255, upload_to=properties.models._media_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'pdf', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
