# Generated by Django 5.2.4 on 2026-06-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_unit_show_publicly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='show_publicly',
        ),
    ]
