# Generated by Django 5.2.4 on 2026-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_remove_unit_show_publicly'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='show_publicly',
            field=models.BooleanField(default=True, help_text='If unchecked, this unit will not appear in WhatsApp/public vacancy lists.', verbose_name='Show in Public Vacancy List'),
        ),
    ]
