# Generated by Django 5.2.4 on 2026-07-01 21:33

import properties.models
from django.db import migrations, models


def populate_existing_police_fields(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for property_obj in Property.objects.all().only('pk', 'property_name'):
        property_obj.house_no = property_obj.property_name or ''
        property_obj.street_no = '5'
        property_obj.colony = 'Golden Jubilee Society'
        property_obj.road = 'GT Road'
        property_obj.covered_area_type = 'Portion'
        property_obj.police_station = 'Morgha'
        property_obj.police_division = 'Pothohar'
        property_obj.police_circle = 'Civil Line'
        property_obj.zila = 'Rawalpindi'
        property_obj.save(update_fields=[
            'house_no',
            'street_no',
            'colony',
            'road',
            'covered_area_type',
            'police_station',
            'police_division',
            'police_circle',
            'zila',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_unit_show_publicly'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='colony',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='covered_area_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='property',
            name='house_no',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_owner_photo_upload_to),
        ),
        migrations.AddField(
            model_name='property',
            name='police_circle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='police_division',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='police_station',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='road',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='street_no',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='property',
            name='zila',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(populate_existing_police_fields, migrations.RunPython.noop),
    ]
