# Generated by Django 5.2.4 on 2026-07-13 16:02

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_mark_requested_smart_meter_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='caretaker_cnic',
            field=core.model_fields.NormalizedCNICField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='caretaker_phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_cnic',
            field=core.model_fields.NormalizedCNICField(max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32, null=True),
        ),
    ]
