# Generated by Django 5.2.4 on 2026-07-14 16:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def copy_existing_unit_building_types(apps, schema_editor):
    BuildingType = apps.get_model("properties", "BuildingType")
    Unit = apps.get_model("properties", "Unit")
    TenantInterestType = apps.get_model("tenants", "TenantInterestType")

    mapping = {}
    for interest_type in TenantInterestType.objects.all().order_by("sort_order", "id"):
        building_type = BuildingType.objects.filter(code=interest_type.code).first()
        if building_type is None:
            name = interest_type.name
            if BuildingType.objects.filter(name=name).exists():
                name = f"{name} ({interest_type.code})"
            building_type = BuildingType.objects.create(
                name=name,
                code=interest_type.code,
                inspection_incomplete_charge=interest_type.inspection_incomplete_charge,
                key_card_not_returned_charge=interest_type.key_card_not_returned_charge,
                sort_order=interest_type.sort_order,
                is_active=interest_type.is_active,
            )
        mapping[interest_type.pk] = building_type.pk

    for interest_type_id, building_type_id in mapping.items():
        Unit.objects.filter(
            interest_type_id=interest_type_id, building_type_id__isnull=True
        ).update(building_type_id=building_type_id)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_unit_move_out_charges'),
        ('tenants', '0023_tenantinteresttype_move_out_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('inspection_incomplete_charge', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Default move-out charge when inspection is not completed.', max_digits=10)),
                ('key_card_not_returned_charge', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Default move-out charge when keys or key cards are not returned.', max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Building Type',
                'verbose_name_plural': 'Building Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='building_type',
            field=models.ForeignKey(blank=True, help_text='Building type used for unit classification and move-out charge defaults.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='properties.buildingtype'),
        ),
        migrations.RunPython(
            copy_existing_unit_building_types,
            migrations.RunPython.noop,
        ),
    ]
