# Generated by Django 5.2.4 on 2026-07-18 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_backfill_unit_building_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='welcome_bank_account_mode',
            field=models.CharField(choices=[('selected', 'Selected account only'), ('all', 'All active accounts')], default='selected', help_text='Choose whether tenant welcome messages include the selected account or every active account.', max_length=12),
        ),
        migrations.CreateModel(
            name='PropertyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_label', models.CharField(default='Primary Account', help_text='A short label such as Rent Account or Maintenance Account.', max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_title', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('iban', models.CharField(blank=True, max_length=80)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('additional_details', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Selected account used when the welcome-message mode is Selected account only.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='properties.property')),
            ],
            options={
                'ordering': ['sort_order', 'account_label', 'id'],
                'constraints': [models.UniqueConstraint(fields=('property', 'account_label'), name='uniq_property_bank_account_label')],
            },
        ),
    ]
