# Generated by Django 5.2.4 on 2026-08-13 18:05

import posixpath

from django.db import migrations


FIELD_SUBFOLDERS = (
    ("file", "original"),
    ("stamped_file", "stamped"),
    ("thumbnail", "thumbs"),
)


def _name_part(value, fallback="item", max_len=42):
    """Frozen copy of the UnitMedia path normalization used at migration time."""
    value = str(value or fallback).strip()
    safe = "".join(ch if ch.isalnum() else "-" for ch in value)
    safe = "-".join(part for part in safe.split("-") if part)
    return (safe or fallback)[:max_len]


def _canonical_path(base, subfolder, old_name):
    filename = posixpath.basename((old_name or "").replace("\\", "/"))
    if not filename:
        return old_name
    return posixpath.join(base, subfolder, filename)


def forwards(apps, schema_editor):
    UnitMedia = apps.get_model("properties", "UnitMedia")
    database_alias = schema_editor.connection.alias
    queryset = (
        UnitMedia.objects.using(database_alias)
        .select_related("unit__property")
        .order_by("pk")
    )

    for media in queryset.iterator():
        property_name = _name_part(
            media.unit.property.property_name,
            "property",
        )
        unit_name = _name_part(
            media.unit.unit_number,
            f"unit-{media.unit_id}",
        )
        canonical_base = f"properties/{property_name}/units/{unit_name}"
        updates = {}

        for field_name, subfolder in FIELD_SUBFOLDERS:
            old_name = str(getattr(media, field_name) or "")
            if not old_name:
                continue
            new_name = _canonical_path(canonical_base, subfolder, old_name)
            if new_name != old_name:
                updates[field_name] = new_name

        if updates:
            UnitMedia.objects.using(database_alias).filter(pk=media.pk).update(
                **updates
            )


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0027_unit_internet_and_security_deposit_amount"),
    ]

    # Reverse is intentionally a no-op. Multiple legacy directory layouts existed,
    # so the exact prior UnitMedia paths cannot be reconstructed deterministically.
    # Production rollback must restore the pre-deployment database backup.
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
