# Generated by Django 5.2.4 on 2026-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_reorganize_unit_media_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electricity_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional property electricity-rate override. Override order: Global, Property, Unit, Meter, then Lease; the last nonblank value wins.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='electricity_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional unit electricity-rate override. Override order: Global, Property, Unit, Meter, then Lease; the last nonblank value wins.', max_digits=10, null=True),
        ),
    ]
