# Generated by Django 5.2.4 on 2026-08-28 23:13

import core.model_fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0101_alter_lease_electric_unit_rate'),
        ('properties', '0031_seed_two_room_flat_move_out_charges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLinkRenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('gallery_type', models.CharField(choices=[('property', 'Property photos'), ('unit', 'Unit photos'), ('lease', 'Lease photos'), ('lease_history', 'Lease history photos')], max_length=20)),
                ('requester_name', models.CharField(max_length=120)),
                ('requester_phone', core.model_fields.NormalizedPhoneField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('original_expires_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_status', models.CharField(blank=True, max_length=24)),
                ('whatsapp_error', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_photo_link_renewals', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_photo_link_renewals', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_link_renewal_requests', to='leases.lease')),
                ('lease_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_link_renewal_requests', to='leases.leaserenewal')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_link_renewal_requests', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_link_renewal_requests', to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PublicPhotoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('gallery_type', models.CharField(choices=[('property', 'Property photos'), ('unit', 'Unit photos'), ('lease', 'Lease photos'), ('lease_history', 'Lease history photos')], max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_photo_links', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_photo_links', to='leases.lease')),
                ('lease_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_photo_links', to='leases.leaserenewal')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_photo_links', to='properties.property')),
                ('renewal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_links', to='properties.photolinkrenewalrequest')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_photo_links', to='properties.unit')),
            ],
        ),
        migrations.AddField(
            model_name='photolinkrenewalrequest',
            name='fresh_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_requests', to='properties.publicphotolink'),
        ),
        migrations.AddIndex(
            model_name='publicphotolink',
            index=models.Index(fields=['gallery_type', 'is_active', 'expires_at'], name='photo_link_type_active_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='photolinkrenewalrequest',
            index=models.Index(fields=['status', 'created_at'], name='photo_req_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='photolinkrenewalrequest',
            index=models.Index(fields=['requester_phone', 'created_at'], name='photo_req_phone_created_idx'),
        ),
        migrations.AddIndex(
            model_name='photolinkrenewalrequest',
            index=models.Index(fields=['request_ip', 'created_at'], name='photo_req_ip_created_idx'),
        ),
    ]
