# Generated by Django 5.2.4 on 2026-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_photo_link_request_prospect_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='iesco_bill_active',
            field=models.BooleanField(default=True, help_text='Include this unit meter in active IESCO bill fetching when the unit has an active lease.'),
        ),
    ]
