# Generated by Django 5.2.4 on 2026-07-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maintenancehandymanassignment',
            name='one_current_handyman_assignment_per_request',
        ),
    ]
