# Generated by Django 5.2.4 on 2026-07-13 16:02

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0003_seed_categories_and_sample_handyman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanprofile',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='handymanprofile',
            name='whatsapp_number',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='handymanrating',
            name='tenant_phone_snapshot',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=40),
        ),
    ]
