# Generated by Django 5.2.4 on 2026-07-01 18:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import handyman.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0058_leaselatefeesettings'),
        ('maintenance', '0008_alter_maintenancerequestmedia_file'),
        ('properties', '0018_unit_show_publicly'),
        ('tenants', '0017_alter_tenant_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Handyman categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HandymanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=handyman.models.handyman_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'])])),
                ('id_card_front', models.ImageField(blank=True, max_length=255, null=True, upload_to=handyman.models.handyman_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'])])),
                ('id_card_back', models.ImageField(blank=True, max_length=255, null=True, upload_to=handyman.models.handyman_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='handymen', to='handyman.handymancategory')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handyman_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_preferred', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceHandymanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('tenant_notified_at', models.DateTimeField(blank=True, null=True)),
                ('handyman_notified_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handyman_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='handyman.handymanprofile')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handyman_assignments', to='maintenance.maintenancerequest')),
            ],
            options={
                'ordering': ['-is_current', '-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HandymanJobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=handyman.models.handyman_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('attachment_type', models.CharField(choices=[('invoice', 'Invoice'), ('job_photo', 'Job Photo')], max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('whatsapp_media_id', models.CharField(blank=True, max_length=160)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='handyman.maintenancehandymanassignment')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HandymanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('property_name_snapshot', models.CharField(blank=True, max_length=160)),
                ('unit_name_snapshot', models.CharField(blank=True, max_length=80)),
                ('tenant_name_snapshot', models.CharField(blank=True, max_length=160)),
                ('tenant_phone_snapshot', models.CharField(blank=True, max_length=40)),
                ('job_title_snapshot', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='handyman.handymanprofile')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handyman_ratings', to='leases.lease')),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handyman_ratings', to='maintenance.maintenancerequest')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handyman_ratings', to='properties.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handyman_ratings', to='tenants.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handyman_ratings', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('handyman', 'maintenance_request', 'tenant')},
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancehandymanassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('maintenance_request',), name='one_current_handyman_assignment_per_request'),
        ),
    ]
