# Generated by Django 5.2.4 on 2026-06-06 00:12

import django.core.validators
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancerequestmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequestmedia',
            name='file',
            field=models.FileField(max_length=255, upload_to=maintenance.models.maintenance_media_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'pdf', 'mp4', 'mov', 'avi', 'mkv', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'csv'])]),
        ),
    ]
