# Generated by Django 5.2.4 on 2026-06-06 09:05

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_CATEGORIES = [
    "General",
    "Electric",
    "Plumbing",
    "Paint",
    "Appliance",
    "Cleaning",
    "Security",
    "Other",
]


def seed_and_backfill_categories(apps, schema_editor):
    MaintenanceCategory = apps.get_model("maintenance", "MaintenanceCategory")
    MaintenanceRequest = apps.get_model("maintenance", "MaintenanceRequest")

    category_by_name = {}
    for index, name in enumerate(DEFAULT_CATEGORIES, start=1):
        category, _ = MaintenanceCategory.objects.get_or_create(
            name=name,
            defaults={"sort_order": index * 10, "is_active": True},
        )
        category_by_name[name.lower()] = category

    for request_obj in MaintenanceRequest.objects.all().iterator():
        raw_name = (request_obj.category or "General").strip() or "General"
        display_name = raw_name.replace("_", " ").replace("-", " ").title()
        category = category_by_name.get(display_name.lower())
        if category is None:
            category, _ = MaintenanceCategory.objects.get_or_create(
                name=display_name,
                defaults={"sort_order": 50, "is_active": True},
            )
            category_by_name[display_name.lower()] = category
        request_obj.category_ref_id = category.pk
        request_obj.category = category.name
        request_obj.save(update_fields=["category_ref", "category"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancerequest_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Maintenance categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=80),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='maintenance.maintenancecategory'),
        ),
        migrations.RunPython(seed_and_backfill_categories, noop_reverse),
    ]
