# Generated by Django 5.2.4 on 2026-06-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='tenant',
        ),
    ]
