# Generated by Django 5.2.4 on 2026-06-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_remove_maintenancerequest_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='building',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='lease',
        ),
    ]
