# Generated by Django 5.2.4 on 2026-06-29 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0014_securitydeposittransaction_deduction_amount_and_more'),
        ('leases', '0047_defaultclause_category_and_more'),
        ('maintenance', '0008_alter_maintenancerequestmedia_file'),
        ('payments', '0006_alter_allocationauditlog_changed_by_and_more'),
        ('tenants', '0017_alter_tenant_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('status', 'Status')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('conversation_id', models.CharField(blank=True, max_length=120)),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('template_name', models.CharField(blank=True, max_length=120)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('document', 'Document'), ('image', 'Image'), ('pdf', 'PDF'), ('webhook', 'Webhook'), ('status', 'Status')], default='text', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='pending', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('error_text', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whatsapp_messages', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='invoices.invoice')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='leases.lease')),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='maintenance.maintenancerequest')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='payments.payment')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction', 'status'], name='whatsapp_wh_directi_9c637a_idx'), models.Index(fields=['phone_number', 'created_at'], name='whatsapp_wh_phone_n_2a1267_idx'), models.Index(fields=['scheduled_for'], name='whatsapp_wh_schedul_1b063f_idx')],
            },
        ),
    ]
