# Generated by Django 5.2.4 on 2026-06-29 04:16

import django.db.models.deletion
import whatsapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0047_defaultclause_category_and_more'),
        ('maintenance', '0008_alter_maintenancerequestmedia_file'),
        ('payments', '0006_alter_allocationauditlog_changed_by_and_more'),
        ('properties', '0015_alter_propertymedia_file_alter_unitmedia_file'),
        ('tenants', '0017_alter_tenant_updated_at'),
        ('whatsapp', '0002_whatsappwebhooklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('pending_state', models.CharField(blank=True, max_length=80)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending_admin', 'Pending admin'), ('archived', 'Archived')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='leases.lease')),
                ('selected_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='properties.property')),
                ('selected_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='properties.unit')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('intent', models.CharField(blank=True, max_length=80)),
                ('ai_prompt', models.TextField(blank=True)),
                ('ai_response', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='whatsapp.whatsappmessagelog')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='whatsapp.whatsappconversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingWhatsAppMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('file', models.FileField(max_length=255, upload_to=whatsapp.models.whatsapp_pending_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=30)),
                ('whatsapp_media_id', models.CharField(blank=True, max_length=160)),
                ('purpose', models.CharField(choices=[('property', 'Property Photos'), ('unit', 'Unit Photos'), ('lease', 'Lease Documents'), ('maintenance', 'Maintenance'), ('payment', 'Payment'), ('other', 'Other')], default='other', max_length=20)),
                ('ai_confidence', models.PositiveSmallIntegerField(default=0)),
                ('ai_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.lease')),
                ('original_whatsapp_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_media', to='whatsapp.whatsappmessagelog')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unit')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_media', to='whatsapp.whatsappconversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingWhatsAppMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('issue_type', models.CharField(blank=True, max_length=80)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ai_confidence', models.PositiveSmallIntegerField(default=0)),
                ('ai_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_pending_sources', to='maintenance.maintenancerequest')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.lease')),
                ('original_whatsapp_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_maintenance', to='whatsapp.whatsappmessagelog')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unit')),
                ('media', models.ManyToManyField(blank=True, related_name='maintenance_submissions', to='whatsapp.pendingwhatsappmedia')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_maintenance', to='whatsapp.whatsappconversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingWhatsAppPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('screenshot', models.FileField(blank=True, max_length=255, null=True, upload_to=whatsapp.models.whatsapp_pending_upload_to)),
                ('ocr_json', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('bank_information', models.JSONField(blank=True, default=dict)),
                ('ai_confidence', models.PositiveSmallIntegerField(default=0)),
                ('ai_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed by tenant'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confirmed_by_tenant', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_whatsapp_payments', to=settings.AUTH_USER_MODEL)),
                ('created_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_pending_sources', to='payments.payment')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.lease')),
                ('original_whatsapp_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payments', to='whatsapp.whatsappmessagelog')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unit')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payments', to='whatsapp.whatsappconversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='whatsapp_pe_status_b560f0_idx'), models.Index(fields=['phone', 'created_at'], name='whatsapp_pe_phone_af245e_idx')],
            },
        ),
    ]
