# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0004_role_based_assistant_foundation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappexternallinktoken",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("tenant_registration", "Tenant registration form"),
                    ("lease_creation", "Lease creation form"),
                    ("agreement_view", "Agreement view link"),
                    ("agreement_edit", "Agreement edit link"),
                    ("invoice_view", "Invoice view link"),
                    ("invoice_pdf", "Invoice PDF link"),
                    ("ledger_view", "Ledger view link"),
                    ("payment_receipt_upload", "Payment receipt upload"),
                    ("maintenance_photo_upload", "Maintenance photo upload"),
                ],
                max_length=40,
            ),
        ),
    ]
