# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0006_alter_whatsappexternallinktoken_link_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="body_parameters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="button_parameter",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="whatsappconversation",
            name="last_inbound_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappconversation",
            name="last_inbound_message_id",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
