# Generated by Codex on 2026-07-01

from django.db import migrations, models


UTILITY_TEMPLATES = [
    {
        "key": "invoice_notice",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} invoice amount\n{{4}} due date",
        "body_variables": ["tenant name", "property / unit", "invoice amount", "due date"],
        "button_label": "View Invoice",
        "button_parameter_source": "Signed public invoice token",
    },
    {
        "key": "payment_confirmation",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} payment amount\n{{4}} receipt number",
        "body_variables": ["tenant name", "property / unit", "payment amount", "receipt number"],
        "button_label": "View Receipt",
        "button_parameter_source": "Signed public payment receipt token",
    },
    {
        "key": "balance_reminder",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} outstanding balance",
        "body_variables": ["tenant name", "property / unit", "outstanding balance"],
        "button_label": "View Ledger",
        "button_parameter_source": "WhatsAppExternalLinkToken ledger token",
    },
    {
        "key": "lease_ledger_link",
        "body_text": "{{1}} tenant name\n{{2}} property / unit",
        "body_variables": ["tenant name", "property / unit"],
        "button_label": "Open Ledger",
        "button_parameter_source": "WhatsAppExternalLinkToken ledger token",
    },
    {
        "key": "rent_due_reminder",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} amount due\n{{4}} due date",
        "body_variables": ["tenant name", "property / unit", "amount due", "due date"],
        "button_label": "Pay / View Invoice",
        "button_parameter_source": "Signed public invoice token",
    },
    {
        "key": "lease_expiry_notice",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} lease end date",
        "body_variables": ["tenant name", "property / unit", "lease end date"],
        "button_label": "View Lease",
        "button_parameter_source": "WhatsAppExternalLinkToken agreement/lease token",
    },
    {
        "key": "lease_renewal_offer",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} lease end date",
        "body_variables": ["tenant name", "property / unit", "lease end date"],
        "button_label": "View Renewal",
        "button_parameter_source": "WhatsAppExternalLinkToken agreement/lease token",
    },
    {
        "key": "maintenance_request_received",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} request number",
        "body_variables": ["tenant name", "property / unit", "request number"],
        "button_label": "View Request",
        "button_parameter_source": "Signed maintenance confirmation token",
    },
    {
        "key": "maintenance_update",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} maintenance status",
        "body_variables": ["tenant name", "property / unit", "maintenance status"],
        "button_label": "",
        "button_parameter_source": "",
    },
    {
        "key": "maintenance_completed",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} completion date",
        "body_variables": ["tenant name", "property / unit", "completion date"],
        "button_label": "",
        "button_parameter_source": "",
    },
    {
        "key": "inspection_schedule",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} inspection date/time",
        "body_variables": ["tenant name", "property / unit", "inspection date/time"],
        "button_label": "View Inspection",
        "button_parameter_source": "Inspection public token",
    },
    {
        "key": "inspection_report_ready",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} report date",
        "body_variables": ["tenant name", "property / unit", "report date"],
        "button_label": "Open Report",
        "button_parameter_source": "Inspection public token",
    },
    {
        "key": "agreement_ready",
        "body_text": "{{1}} tenant name\n{{2}} property / unit",
        "body_variables": ["tenant name", "property / unit"],
        "button_label": "Open Agreement",
        "button_parameter_source": "WhatsAppExternalLinkToken agreement token",
    },
    {
        "key": "tenant_registration",
        "body_text": "{{1}} tenant name",
        "body_variables": ["tenant name"],
        "button_label": "Complete Registration",
        "button_parameter_source": "Signed tenant registration token",
    },
    {
        "key": "lease_application",
        "body_text": "{{1}} tenant name",
        "body_variables": ["tenant name"],
        "button_label": "Open Application",
        "button_parameter_source": "WhatsAppExternalLinkToken lease application token",
    },
    {
        "key": "meter_reading_available",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} electric charges",
        "body_variables": ["tenant name", "property / unit", "electric charges"],
        "button_label": "View Utility Bill",
        "button_parameter_source": "Signed utility bill token",
    },
    {
        "key": "water_bill_added",
        "body_text": "{{1}} tenant name\n{{2}} property / unit\n{{3}} water charges",
        "body_variables": ["tenant name", "property / unit", "water charges"],
        "button_label": "View Charges",
        "button_parameter_source": "Signed utility charge token",
    },
    {
        "key": "account_notice",
        "body_text": "{{1}} tenant name",
        "body_variables": ["tenant name"],
        "button_label": "View Details",
        "button_parameter_source": "Signed account details token",
    },
]


def seed_utility_templates(apps, schema_editor):
    WhatsAppUtilityTemplate = apps.get_model("whatsapp", "WhatsAppUtilityTemplate")
    for item in UTILITY_TEMPLATES:
        WhatsAppUtilityTemplate.objects.get_or_create(
            key=item["key"],
            defaults={
                "template_name": item["key"],
                "language_code": "en",
                "body_text": item["body_text"],
                "body_variables": item["body_variables"],
                "button_label": item["button_label"],
                "button_parameter_source": item["button_parameter_source"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0007_template_sessions_and_log_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppUtilityTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(choices=[("invoice_notice", "Invoice notice"), ("payment_confirmation", "Payment confirmation"), ("balance_reminder", "Balance reminder"), ("lease_ledger_link", "Lease ledger link"), ("rent_due_reminder", "Rent due reminder"), ("lease_expiry_notice", "Lease expiry notice"), ("lease_renewal_offer", "Lease renewal offer"), ("maintenance_request_received", "Maintenance request received"), ("maintenance_update", "Maintenance update"), ("maintenance_completed", "Maintenance completed"), ("inspection_schedule", "Inspection schedule"), ("inspection_report_ready", "Inspection report ready"), ("agreement_ready", "Agreement ready"), ("tenant_registration", "Tenant registration"), ("lease_application", "Lease application"), ("meter_reading_available", "Meter reading available"), ("water_bill_added", "Water bill added"), ("account_notice", "Account notice")], max_length=80, unique=True)),
                ("template_name", models.CharField(help_text="Approved Meta template name. Usually the same as the key.", max_length=120)),
                ("language_code", models.CharField(default="en", max_length=20)),
                ("body_text", models.TextField(blank=True, help_text="Local reference copy of the approved Meta body. Changing this does not update Meta automatically.")),
                ("body_variables", models.JSONField(blank=True, default=list)),
                ("button_label", models.CharField(blank=True, max_length=120)),
                ("button_parameter_source", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.RunPython(seed_utility_templates, migrations.RunPython.noop),
    ]
