# Generated by Django 5.2.4 on 2026-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_whatsapputilitytemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapputilitytemplate',
            name='key',
            field=models.CharField(choices=[('invoice_notice', 'Invoice notice'), ('payment_confirmation', 'Payment confirmation'), ('balance_reminder', 'Balance reminder'), ('late_fee_reminder', 'Late fee reminder'), ('lease_ledger_link', 'Lease ledger link'), ('rent_due_reminder', 'Rent due reminder'), ('lease_expiry_notice', 'Lease expiry notice'), ('lease_renewal_offer', 'Lease renewal offer'), ('maintenance_request_received', 'Maintenance request received'), ('maintenance_update', 'Maintenance update'), ('maintenance_completed', 'Maintenance completed'), ('inspection_schedule', 'Inspection schedule'), ('inspection_report_ready', 'Inspection report ready'), ('agreement_ready', 'Agreement ready'), ('tenant_registration', 'Tenant registration'), ('lease_application', 'Lease application'), ('meter_reading_available', 'Meter reading available'), ('water_bill_added', 'Water bill added'), ('account_notice', 'Account notice')], max_length=80, unique=True),
        ),
    ]
