# Generated by Django 5.2.4 on 2026-07-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_seed_late_fee_reminder_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappexternallinktoken',
            name='link_type',
            field=models.CharField(choices=[('tenant_registration', 'Tenant registration form'), ('lease_creation', 'Lease creation form'), ('agreement_view', 'Agreement view link'), ('agreement_edit', 'Agreement edit link'), ('invoice_view', 'Invoice view link'), ('invoice_pdf', 'Invoice PDF link'), ('ledger_view', 'Ledger view link'), ('lease_family_add', 'Lease family member form'), ('police_verification', 'Police verification form'), ('payment_receipt_upload', 'Payment receipt upload'), ('maintenance_photo_upload', 'Maintenance photo upload')], max_length=40),
        ),
    ]
