# Generated by Django 5.2.4 on 2026-07-13 15:34

import django.db.models.deletion
import whatsapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0074_agreement_legal_layout_settings'),
        ('properties', '0020_mark_requested_smart_meter_units'),
        ('tenants', '0021_rename_tenants_pen_submiss_6f4b14_idx_tenants_pen_submiss_978b47_idx_and_more'),
        ('whatsapp', '0013_whatsapputilitytemplate_language_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='decision_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='fallback_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='handover_reason',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='handover_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='input_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='whatsappaiinteractionlog',
            name='tool_results_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_whatsapp_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='handover_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='last_ai_confidence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappconversation',
            name='selected_mode',
            field=models.CharField(blank=True, choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('staff', 'Staff'), ('handover', 'Handover')], max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF'), ('webhook', 'Webhook'), ('status', 'Status')], default='text', max_length=30),
        ),
        migrations.CreateModel(
            name='WhatsAppHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=whatsapp.models.whatsapp_handover_reference, max_length=24, unique=True)),
                ('tenant_phone', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('notified', 'Notified'), ('accepted', 'Accepted'), ('waiting_for_tenant', 'Waiting for tenant'), ('waiting_for_staff', 'Waiting for staff'), ('call_requested', 'Call requested'), ('called', 'Called'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('returned_to_ai', 'Returned to AI'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('department', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(max_length=160)),
                ('tenant_message', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_staff_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_tenant_message_at', models.DateTimeField(blank=True, null=True)),
                ('call_requested_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_to_ai_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_whatsapp_handovers', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='whatsapp.whatsappconversation')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unit')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppHandoverMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('tenant', 'Tenant'), ('staff', 'Staff'), ('system', 'System')], max_length=20)),
                ('original_text', models.TextField(blank=True)),
                ('relayed_text', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('relayed', 'Relayed'), ('internal', 'Internal')], default='inbound', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsapphandover')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.pendingwhatsappmedia')),
                ('relayed_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_relayed_messages', to='whatsapp.whatsappmessagelog')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_source_messages', to='whatsapp.whatsappmessagelog')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppStaffRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=80)),
                ('department', models.CharField(choices=[('general', 'General support'), ('accounts', 'Accounts'), ('maintenance', 'Maintenance'), ('leasing', 'Leasing'), ('management', 'Management')], default='general', max_length=30)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsapphandover',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='whatsapp_wh_status_3ab065_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapphandover',
            index=models.Index(fields=['assigned_staff', 'status'], name='whatsapp_wh_assigne_65bad2_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapphandover',
            index=models.Index(fields=['property', 'status'], name='whatsapp_wh_propert_fc4974_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappstaffroutingrule',
            constraint=models.UniqueConstraint(fields=('property', 'department', 'staff_user'), name='unique_whatsapp_staff_route'),
        ),
    ]
