# Generated by Django 5.2.4 on 2026-07-13 16:02

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_whatsappaiinteractionlog_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingwhatsappmaintenance',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingwhatsappmedia',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingwhatsapppayment',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='trusteddeviceregistry',
            name='phone_number',
            field=core.model_fields.NormalizedPhoneField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappaiinteractionlog',
            name='phone_number',
            field=core.model_fields.NormalizedPhoneField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappconversation',
            name='phone_number',
            field=core.model_fields.NormalizedPhoneField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappexternallinktoken',
            name='phone_number',
            field=core.model_fields.NormalizedPhoneField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsapphandover',
            name='tenant_phone',
            field=core.model_fields.NormalizedPhoneField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='phone_number',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappstaffactionlog',
            name='phone_number',
            field=core.model_fields.NormalizedPhoneField(blank=True, db_index=True, max_length=32),
        ),
    ]
