# Generated by Django 5.2.4 on 2026-07-15 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0015_alter_pendingwhatsappmaintenance_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingwhatsappmedia',
            name='batch_key',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pendingwhatsappmedia',
            name='submitted_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_whatsapp_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingwhatsappmedia',
            name='target_kind',
            field=models.CharField(blank=True, choices=[('property_photo', 'Building / Property Photo'), ('unit_photo', 'Unit Photo'), ('lease_photo', 'Lease Gallery Photo'), ('lease_document', 'Lease Document')], max_length=24),
        ),
        migrations.AlterField(
            model_name='whatsappconversation',
            name='selected_mode',
            field=models.CharField(blank=True, choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('staff', 'Staff'), ('handyman', 'Handyman'), ('handover', 'Handover')], max_length=20),
        ),
    ]
