# Generated by Django 5.2.4 on 2025-07-08 09:39

import django.db.models.deletion
import leases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('society_maintenance', models.DecimalField(blank=True, decimal_places=2, default=1200, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('terms', models.TextField(blank=True, default=leases.models.default_lease_terms, help_text='Detailed terms and conditions of the lease agreement')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_agreement', models.FileField(blank=True, null=True, upload_to='leases/agreements/')),
                ('security_deposit_paid', models.BooleanField(default=False)),
                ('security_deposit_returned', models.BooleanField(default=False)),
                ('security_deposit_return_date', models.DateField(blank=True, null=True)),
                ('security_deposit_return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit_return_notes', models.TextField(blank=True)),
                ('rent_increase_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage increase applied when lease renews', max_digits=5, verbose_name='Rent Increase Percentage (%)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.unit')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
