# Generated by Django 5.2.4 on 2025-07-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='generated_agreement',
            field=models.FileField(blank=True, help_text='Auto-generated lease agreement', null=True, upload_to='leases/agreements/generated/'),
        ),
        migrations.AddField(
            model_name='lease',
            name='is_agreement_signed',
            field=models.BooleanField(default=False, help_text='Mark if agreement has been signed'),
        ),
    ]
