# Generated by Django 5.2.4 on 2025-07-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_generated_agreement_lease_is_agreement_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='generated_agreement_docx',
            field=models.FileField(blank=True, help_text='Auto-generated lease agreement (Word)', null=True, upload_to='leases/agreements/generated/'),
        ),
        migrations.AddField(
            model_name='lease',
            name='generated_agreement_pdf',
            field=models.FileField(blank=True, help_text='Auto-generated lease agreement (PDF)', null=True, upload_to='leases/agreements/generated/'),
        ),
        migrations.AddField(
            model_name='lease',
            name='generated_date',
            field=models.DateTimeField(blank=True, help_text='When the agreement was generated', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='signed_copy',
            field=models.FileField(blank=True, help_text='Scanned signed agreement with thumb impression', null=True, upload_to='leases/agreements/signed/'),
        ),
    ]
