# Generated by Django 5.2.4 on 2025-07-25 12:41

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_lease_generated_agreement_docx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', CKEditor5Field(
                    help_text='Use {{ variables }} for dynamic content')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
