# Generated by Django 5.2.4 on 2025-07-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_leasetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasetemplate',
            name='content',
        ),
        migrations.AddField(
            model_name='lease',
            name='agreement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasetemplate',
            name='clauses',
            field=models.JSONField(default=list, help_text='JSON array of clause templates'),
        ),
        migrations.CreateModel(
            name='LeaseAgreementClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.PositiveIntegerField()),
                ('template_text', models.TextField()),
                ('is_customized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='leases.lease')),
            ],
            options={
                'ordering': ['clause_number'],
                'unique_together': {('lease', 'clause_number')},
            },
        ),
    ]
