# Generated by Django 5.2.4 on 2025-07-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_remove_leasetemplate_content_lease_agreement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='electricity_meter_reading',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='water_meter_reading',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='witness1_cnic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='witness1_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='witness2_cnic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='witness2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
