# Generated by Django 5.2.4 on 2025-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_lease_electricity_meter_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='early_termination_penalty',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='key_replacement_cost',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='keys_issued',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='min_lease_occupancy_months',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='lease',
            name='security_installment_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='security_installment_1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='security_installment_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='security_installment_2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='generated_agreement',
            field=models.FileField(blank=True, help_text='Auto-generated lease agreement', null=True, upload_to='leases/sign_agreements/', verbose_name='Signed Agreement'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='signed_agreement',
            field=models.FileField(blank=True, null=True, upload_to='agreements/', verbose_name='Signed Agreement'),
        ),
    ]
