# Generated by Django 5.2.4 on 2025-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_lease_due_date_lease_early_termination_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='inventory_ceiling_fans',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='lease',
            name='inventory_ceiling_lights',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='inventory_exhaust_fans',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lease',
            name='inventory_keys',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lease',
            name='inventory_stove',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lease',
            name='inventory_wardrobes',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lease',
            name='paint_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
