# Generated by Django 5.2.4 on 2025-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0008_lease_inventory_ceiling_fans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='due_date',
            field=models.TextField(blank=True, default='5th of each month.', null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=500.0, max_digits=10, null=True),
        ),
    ]
