# Generated by Django 5.2.4 on 2025-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_alter_lease_due_date_alter_lease_late_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='due_date',
            field=models.CharField(blank=True, default='5th of each month.', max_length=100, null=True),
        ),
    ]
