# Generated by Django 5.2.4 on 2025-07-30 19:51

import leases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0010_alter_lease_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='early_termination_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='electricity_meter_reading',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='inventory_ceiling_fans',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='inventory_ceiling_lights',
            field=models.IntegerField(blank=True, default=16, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='inventory_exhaust_fans',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='inventory_keys',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='inventory_stove',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='inventory_wardrobes',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='key_replacement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='keys_issued',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='min_lease_occupancy_months',
            field=models.PositiveIntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='paint_condition',
            field=models.TextField(blank=True, default='New Paint.', null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_increase_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Percentage increase applied when lease renews', max_digits=5, null=True, verbose_name='Rent Increase Percentage (%)'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='security_deposit_return_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='terms',
            field=models.TextField(blank=True, default=leases.models.default_lease_terms, help_text='Detailed terms and conditions of the lease agreement', null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='water_meter_reading',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='witness1_cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='witness1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='witness2_cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='witness2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
