# Generated by Django 5.2.4 on 2025-07-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0011_alter_lease_early_termination_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='electric_unit_rate',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
