# Generated by Django 5.2.4 on 2025-07-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0012_lease_electric_unit_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='water_meter_reading',
        ),
        migrations.AddField(
            model_name='lease',
            name='gas_meter_reading',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
