# Generated by Django 5.2.4 on 2025-08-23 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0013_remove_lease_water_meter_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('relation', models.CharField(blank=True, max_length=50)),
                ('cnic', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_opt_in', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='leases.lease')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('lease', 'full_name', 'cnic')},
            },
        ),
    ]
