# Generated by Django 5.2.4 on 2025-08-23 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0014_leasefamilymember'),
        ('tenants', '0007_tenant_phone2_tenant_phone3_alter_tenant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=50)),
                ('whatsapp_opt_in', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_families', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__first_name', 'tenant__last_name'],
                'unique_together': {('lease', 'tenant')},
            },
        ),
        migrations.DeleteModel(
            name='LeaseFamilyMember',
        ),
    ]
