# Generated by Django 5.2.4 on 2025-09-20 02:02

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0015_leasefamily_delete_leasefamilymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='condition_photos_signed',
            field=models.FileField(blank=True, help_text='Signed PDF acknowledging move-in photos (PCR)',
                                   null=True, upload_to='leases/condition_photos/signed/', verbose_name='Signed Condition Photos'),
        ),
        migrations.CreateModel(
            name='PropertyConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    default='Move-in Condition Photos', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='condition_report', to='leases.lease')),
            ],
        ),
        migrations.CreateModel(
            name='PCRVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='leases/legacy_videos')),
                ('poster', models.ImageField(blank=True, editable=False, null=True,
                                             upload_to='leases/legacy_posters')),
                ('encoded_mp4', models.FileField(blank=True, editable=False, null=True,
                                                 upload_to='leases/legacy_videos')),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('room', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('processing_status', models.CharField(choices=[
                 ('pending', 'pending'), ('ok', 'ok'), ('error', 'error')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='videos', to='leases.propertyconditionreport')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PCRPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leases/legacy_photos')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True,
                                                upload_to='leases/legacy_thumbs')),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('room', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pcr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='photos', to='leases.propertyconditionreport')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
