# Generated by Django 5.2.4 on 2025-09-20 02:47

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0016_lease_condition_photos_signed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leases/legacy_photos')),
                ('thumbnail', models.ImageField(
                    null=True, upload_to='leases/legacy_thumbs')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='photos', to='leases.lease')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
