# Generated by Django 5.2.4 on 2025-10-30 18:29

import django.core.validators
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0017_leasephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(
                    upload_to='leases/legacy_files',
                    validators=[django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            'jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv']
                    )]
                )),
                ('thumbnail', models.ImageField(
                    null=True,
                    upload_to='leases/legacy_thumbs'
                )),

                ('media_type', models.CharField(choices=[
                 ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='media', to='leases.lease')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='LeasePhoto',
        ),
    ]
