# Generated by Django 5.2.4 on 2025-11-02 01:21

import django.core.validators
import leases.models_lease_photos
import leases.models_pcr
import leases.models_pcr_video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0018_leasemedia_delete_leasephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasemedia',
            name='original_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=leases.models_lease_photos._upload_tmp),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='file',
            field=models.FileField(upload_to=leases.models_lease_photos._upload_tmp, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=leases.models_lease_photos._upload_tmp),
        ),
        migrations.AlterField(
            model_name='pcrphoto',
            name='image',
            field=models.ImageField(upload_to=leases.models_pcr._photo_upload_path),
        ),
        migrations.AlterField(
            model_name='pcrphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=leases.models_pcr._thumb_upload_path),
        ),
        migrations.AlterField(
            model_name='pcrvideo',
            name='encoded_mp4',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=leases.models_pcr_video._video_upload_path),
        ),
        migrations.AlterField(
            model_name='pcrvideo',
            name='file',
            field=models.FileField(upload_to=leases.models_pcr_video._video_upload_path),
        ),
        migrations.AlterField(
            model_name='pcrvideo',
            name='poster',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=leases.models_pcr_video._poster_upload_path),
        ),
    ]
