# Generated by Django 5.2.4 on 2025-11-05 22:57

import django.core.validators
import leases.models_lease_photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0019_leasemedia_original_file_alter_leasemedia_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasemedia',
            name='file',
            field=models.FileField(max_length=120, upload_to=leases.models_lease_photos._upload_tmp, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='original_file',
            field=models.FileField(blank=True, editable=False, max_length=120, null=True, upload_to=leases.models_lease_photos._upload_tmp),
        ),
    ]
