# Generated by Django 5.2.4 on 2025-11-05 23:05

import leases.models_lease_photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0020_alter_leasemedia_file_alter_leasemedia_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasemedia',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, max_length=120, null=True, upload_to=leases.models_lease_photos._upload_tmp),
        ),
    ]
