# Generated by Django 5.2.4 on 2025-11-10 06:32

import django.core.validators
import leases.models_lease_photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0021_alter_leasemedia_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasemedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='file',
            field=models.FileField(max_length=120, upload_to=leases.models_lease_photos._upload_tmp, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=leases.models_lease_photos._upload_tmp),
        ),
    ]
