# Generated by Django 5.2.4 on 2025-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0022_leasemedia_updated_at_alter_leasemedia_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasemedia',
            name='original_file',
        ),
        migrations.AddField(
            model_name='leasemedia',
            name='footer_height_px',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='leasemedia',
            name='static_footer_text',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
