# Generated by Django 5.2.4 on 2025-11-12 20:24

import django.core.validators
import leases.models_lease_photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0023_remove_leasemedia_original_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasemedia',
            name='file',
            field=models.FileField(max_length=255, upload_to=leases.models_lease_photos._upload_tmp, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to=leases.models_lease_photos._upload_tmp),
        ),
    ]
