# Generated by Django 5.2.4 on 2025-11-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0024_alter_leasemedia_file_alter_leasemedia_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.PositiveIntegerField()),
                ('body', models.TextField(help_text='Use {{ }} variables like {{ monthly_rent }}, {{ tenant.full_name }}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['clause_number'],
                'unique_together': {('clause_number', 'is_active')},
            },
        ),
    ]
