# Generated by Django 5.2.4 on 2025-12-09 20:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0025_defaultclause'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='agreement_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), help_text='One-time agreement charges (0 to skip)', max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='internet_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monthly internet charges (0 for none)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='water_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monthly water charges (0 for none)', max_digits=10, null=True),
        ),
    ]
