# Generated by Django 5.2.4 on 2026-02-09 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0026_lease_agreement_charges_lease_internet_charges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultLeaseClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.PositiveIntegerField(unique=True)),
                ('template_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['clause_number'],
            },
        ),
        migrations.CreateModel(
            name='AgreementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('NEW', 'New Agreement'), ('RENEWAL', 'Renewal'), ('AMENDMENT', 'Amendment')], default='NEW', max_length=20)),
                ('agreement_date', models.DateField()),
                ('term_start_date', models.DateField()),
                ('term_end_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('signed_agreement', models.FileField(blank=True, null=True, upload_to='signed_agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_versions', to='leases.lease')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='AgreementClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.PositiveIntegerField()),
                ('template_text', models.TextField()),
                ('agreement_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='leases.agreementversion')),
            ],
            options={
                'ordering': ['clause_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='agreementversion',
            constraint=models.UniqueConstraint(fields=('lease', 'version'), name='uniq_version_per_lease'),
        ),
        migrations.AddConstraint(
            model_name='agreementclause',
            constraint=models.UniqueConstraint(fields=('agreement_version', 'clause_number'), name='uniq_clause_per_version'),
        ),
    ]
