# Generated by Django 5.2.4 on 2026-05-15 23:18

import django.db.models.deletion
import leases.models_renewal
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0027_defaultleaseclause_agreementversion_agreementclause_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_master',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='original_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_leases', to='leases.lease'),
        ),
        migrations.CreateModel(
            name='LeaseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('society_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('internet_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rent_increase_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('generated_agreement_pdf', models.FileField(blank=True, null=True, upload_to=leases.models_renewal.renewal_file_upload_to)),
                ('generated_agreement_docx', models.FileField(blank=True, null=True, upload_to=leases.models_renewal.renewal_file_upload_to)),
                ('signed_copy', models.FileField(blank=True, null=True, upload_to=leases.models_renewal.renewal_file_upload_to)),
                ('is_agreement_signed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_renewals_created', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='leases.lease')),
            ],
            options={
                'ordering': ['renewal_number'],
                'unique_together': {('lease', 'renewal_number')},
            },
        ),
        migrations.CreateModel(
            name='LeaseRenewalClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.PositiveIntegerField()),
                ('template_text', models.TextField()),
                ('is_customized', models.BooleanField(default=False)),
                ('renewal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='leases.leaserenewal')),
            ],
            options={
                'ordering': ['clause_number'],
                'unique_together': {('renewal', 'clause_number')},
            },
        ),
    ]
