# Generated by Django 5.2.4 on 2026-05-16 20:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_original_histories(apps, schema_editor):
    Lease = apps.get_model('leases', 'Lease')
    LeaseRenewal = apps.get_model('leases', 'LeaseRenewal')
    LeaseAgreementClause = apps.get_model('leases', 'LeaseAgreementClause')
    LeaseRenewalClause = apps.get_model('leases', 'LeaseRenewalClause')

    for lease in Lease.objects.all().iterator():
        existing_original = LeaseRenewal.objects.filter(
            lease=lease,
            is_original=True,
        ).first()
        if existing_original:
            continue

        if LeaseRenewal.objects.filter(lease=lease, renewal_number=1).exists():
            for row in LeaseRenewal.objects.filter(lease=lease).order_by('-renewal_number', '-id'):
                row.renewal_number = row.renewal_number + 1
                row.save(update_fields=['renewal_number'])

        history = LeaseRenewal.objects.create(
            lease=lease,
            renewal_number=1,
            is_original=True,
            start_date=lease.start_date,
            end_date=lease.end_date,
            agreement_date=lease.agreement_date or lease.start_date,
            monthly_rent=lease.monthly_rent,
            society_maintenance=lease.society_maintenance,
            water_charges=lease.water_charges or Decimal('0.00'),
            internet_charges=lease.internet_charges or Decimal('0.00'),
            agreement_charges=lease.agreement_charges or Decimal('0.00'),
            security_deposit=lease.security_deposit,
            rent_increase_percent=lease.rent_increase_percent or Decimal('0.00'),
            witness1_name=lease.witness1_name,
            witness1_cnic=lease.witness1_cnic,
            witness2_name=lease.witness2_name,
            witness2_cnic=lease.witness2_cnic,
            terms=lease.terms,
        )

        clauses = []
        for clause in LeaseAgreementClause.objects.filter(lease=lease).order_by('clause_number'):
            clauses.append(LeaseRenewalClause(
                renewal=history,
                clause_number=clause.clause_number,
                template_text=clause.template_text,
                is_customized=clause.is_customized,
            ))
        if clauses:
            LeaseRenewalClause.objects.bulk_create(clauses)


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0028_lease_is_master_lease_original_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserenewal',
            name='agreement_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_renewals_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='witness1_cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='witness1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='witness2_cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='witness2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(backfill_original_histories, migrations.RunPython.noop),
    ]
