# Generated by Django 5.2.4 on 2026-05-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0032_sync_default_clauses_from_hardcoded'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Placeholder key without brackets, e.g. MONTHLY_RENT.', max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='General', max_length=80)),
                ('source_type', models.CharField(choices=[('system', 'System'), ('custom', 'Custom'), ('manual', 'Manual')], default='system', max_length=20)),
                ('resolver_key', models.CharField(blank=True, max_length=120)),
                ('django_path', models.CharField(blank=True, max_length=180)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'key'],
            },
        ),
    ]
