# Generated by Django 5.2.4 on 2026-05-17 01:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import leases.models_lease_photos
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0034_seed_agreement_placeholders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leasemedia',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='leasemedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leasemedia',
            name='lease_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='leases.leaserenewal'),
        ),
        migrations.AddField(
            model_name='leasemedia',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leasemedia',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leasemedia',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leasemedia',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_media_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='file',
            field=models.FileField(max_length=255, upload_to=leases.models_lease_photos._upload_tmp, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], max_length=10),
        ),
    ]
