# Generated by Django 5.2.4 on 2026-05-17 01:43

from django.db import migrations, models


def seed_whatsapp_templates(apps, schema_editor):
    WhatsAppTemplate = apps.get_model('leases', 'WhatsAppTemplate')
    templates = [
        ('tenant_welcome', 'Tenant welcome message'),
        ('vacancy', 'Vacancy message'),
        ('rent_reminder', 'Rent reminder'),
        ('payment_received', 'Payment received'),
        ('balance_reminder', 'Balance reminder'),
        ('repair_request_reminder', 'Repair request reminder'),
        ('police_verification_reminder', 'Police verification reminder'),
        ('agreement_signing_reminder', 'Agreement signing reminder'),
    ]
    for template_type, name in templates:
        WhatsAppTemplate.objects.get_or_create(
            template_type=template_type,
            defaults={
                'name': name,
                'body': '',
                'is_active': True,
            },
        )


def unseed_whatsapp_templates(apps, schema_editor):
    WhatsAppTemplate = apps.get_model('leases', 'WhatsAppTemplate')
    WhatsAppTemplate.objects.filter(body='').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0035_alter_leasemedia_options_leasemedia_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('tenant_welcome', 'Tenant welcome message'), ('vacancy', 'Vacancy message'), ('rent_reminder', 'Rent reminder'), ('payment_received', 'Payment received'), ('balance_reminder', 'Balance reminder'), ('repair_request_reminder', 'Repair request reminder'), ('police_verification_reminder', 'Police verification reminder'), ('agreement_signing_reminder', 'Agreement signing reminder')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, help_text='Use placeholders like [TENANT_NAME], [UNIT_NUMBER], or custom placeholders.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type'],
            },
        ),
        migrations.RunPython(seed_whatsapp_templates, unseed_whatsapp_templates),
    ]
