# Generated by Django 5.2.4 on 2026-05-18 06:23

import django.db.models.deletion
import leases.models_renewal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0036_whatsapptemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='lease',
                    name='police_verification_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lease',
                    name='police_verification_document',
                    field=models.FileField(blank=True, null=True, upload_to='leases/police_verification/'),
                ),
                migrations.AddField(
                    model_name='lease',
                    name='police_verification_follow_up_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lease',
                    name='police_verification_remarks',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='lease',
            name='police_verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('follow_up', 'Follow Up')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='police_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_verified_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_document',
            field=models.FileField(blank=True, null=True, upload_to=leases.models_renewal.renewal_file_upload_to),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('follow_up', 'Follow Up')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_verified_lease_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
