# Generated by Django 5.2.4 on 2026-05-18 06:23

import django.db.models.deletion
import leases.models_renewal
from django.conf import settings
from django.db import migrations, models


def ensure_lease_police_columns(apps, schema_editor):
    """Create legacy state-only Lease columns on fresh databases, without touching existing columns."""
    Lease = apps.get_model("leases", "Lease")
    table_name = Lease._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    existing = {column.name for column in description}
    for field_name in (
        "police_verification_date",
        "police_verification_document",
        "police_verification_follow_up_date",
        "police_verification_remarks",
    ):
        field = Lease._meta.get_field(field_name)
        if field.column not in existing:
            schema_editor.add_field(Lease, field)
            existing.add(field.column)



class Migration(migrations.Migration):

    # This historical migration performs conditional DDL for fresh databases.
    # MySQL cannot execute that DDL inside Django's atomic migration wrapper.
    atomic = False

    dependencies = [
        ('leases', '0036_whatsapptemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='lease',
                    name='police_verification_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lease',
                    name='police_verification_document',
                    field=models.FileField(blank=True, null=True, upload_to='leases/police_verification/'),
                ),
                migrations.AddField(
                    model_name='lease',
                    name='police_verification_follow_up_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lease',
                    name='police_verification_remarks',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(ensure_lease_police_columns, migrations.RunPython.noop),
        migrations.AddField(
            model_name='lease',
            name='police_verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('follow_up', 'Follow Up')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='police_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_verified_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_document',
            field=models.FileField(blank=True, null=True, upload_to=leases.models_renewal.renewal_file_upload_to),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('follow_up', 'Follow Up')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='police_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_verified_lease_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
