# Generated by Django 5.2.4 on 2026-05-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0037_lease_police_verification_date_and_more'),
        ('properties', '0013_propertymedia_unitmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseUnitOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_occupancies', to='leases.lease')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_occupancies', to='properties.unit')),
            ],
            options={
                'ordering': ['-move_in_date', '-id'],
                'indexes': [models.Index(fields=['lease', 'move_in_date'], name='leases_leas_lease_i_31419f_idx'), models.Index(fields=['unit', 'move_in_date'], name='leases_leas_unit_id_126120_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('move_out_date__isnull', True), ('move_out_date__gte', models.F('move_in_date')), _connector='OR'), name='lease_occupancy_out_after_in'), models.UniqueConstraint(condition=models.Q(('move_out_date__isnull', True)), fields=('lease',), name='one_active_occupancy_per_lease')],
            },
        ),
    ]
