# Generated by Django 5.2.4 on 2026-05-25 13:15

from django.db import migrations, models


def populate_active_lease_keys(apps, schema_editor):
    LeaseUnitOccupancy = apps.get_model("leases", "LeaseUnitOccupancy")
    seen = set()
    for occupancy in (
        LeaseUnitOccupancy.objects
        .filter(move_out_date__isnull=True)
        .order_by("lease_id", "-move_in_date", "-id")
    ):
        if occupancy.lease_id in seen:
            continue
        seen.add(occupancy.lease_id)
        LeaseUnitOccupancy.objects.filter(pk=occupancy.pk).update(active_lease_key=occupancy.lease_id)


def clear_active_lease_keys(apps, schema_editor):
    LeaseUnitOccupancy = apps.get_model("leases", "LeaseUnitOccupancy")
    LeaseUnitOccupancy.objects.update(active_lease_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0039_backfill_lease_unit_occupancy'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaseunitoccupancy',
            name='one_active_occupancy_per_lease',
        ),
        migrations.AddField(
            model_name='leaseunitoccupancy',
            name='active_lease_key',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Internal DB guard: lease id while active, NULL when closed.', null=True, unique=True),
        ),
        migrations.RunPython(populate_active_lease_keys, clear_active_lease_keys),
    ]
