# Generated by Django 5.2.4 on 2026-06-03 14:06

import django.core.validators
import django.db.models.deletion
import leases.models
from django.db import migrations, models


DOCUMENT_CATEGORIES = [
    ("tenant_photo", "Tenant Photo", 10),
    ("cnic_front", "CNIC Front", 20),
    ("cnic_back", "CNIC Back", 30),
    ("lease_agreement", "Lease Agreement", 40),
    ("lease_renewal_agreement", "Lease Renewal Agreement", 50),
    ("police_verification", "Police Verification", 60),
    ("property_condition_report", "Property Condition Report", 70),
    ("utility_bill", "Utility Bill", 80),
    ("income_proof", "Income Proof", 90),
    ("employment_letter", "Employment Letter", 100),
    ("reference_letter", "Reference Letter", 110),
    ("other", "Other", 200),
]


RELATION_MAP = {
    "spouse": "spouse",
    "wife": "spouse",
    "husband": "spouse",
    "son": "son",
    "daughter": "daughter",
    "father": "father",
    "mother": "mother",
    "brother": "brother",
    "sister": "sister",
    "uncle": "uncle",
    "aunt": "aunt",
    "grandfather": "grandfather",
    "grandmother": "grandmother",
    "cousin": "cousin",
    "nephew": "nephew",
    "niece": "niece",
}


def seed_document_categories(apps, schema_editor):
    LeaseDocumentCategory = apps.get_model("leases", "LeaseDocumentCategory")
    for code, name, sort_order in DOCUMENT_CATEGORIES:
        LeaseDocumentCategory.objects.update_or_create(
            code=code,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )


def copy_legacy_family_members(apps, schema_editor):
    LeaseFamily = apps.get_model("leases", "LeaseFamily")
    LeaseFamilyMember = apps.get_model("leases", "LeaseFamilyMember")
    for legacy in LeaseFamily.objects.select_related("lease", "tenant"):
        relationship = RELATION_MAP.get((legacy.relation or "").strip().lower(), "other")
        LeaseFamilyMember.objects.get_or_create(
            lease_id=legacy.lease_id,
            primary_tenant_id=legacy.lease.tenant_id,
            family_member_id=legacy.tenant_id,
            defaults={"relationship": relationship, "lives_with_tenant": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0042_leasedocumentcategory'),
        ('tenants', '0010_tenant_city_tenant_country_tenant_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasedocument',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='category',
            field=models.CharField(choices=[('tenant_photo', 'Tenant Photo'), ('cnic_front', 'CNIC Front'), ('cnic_back', 'CNIC Back'), ('lease_agreement', 'Lease Agreement'), ('lease_renewal_agreement', 'Lease Renewal Agreement'), ('police_verification', 'Police Verification'), ('property_condition_report', 'Property Condition Report'), ('utility_bill', 'Utility Bill'), ('income_proof', 'Income Proof'), ('employment_letter', 'Employment Letter'), ('reference_letter', 'Reference Letter'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=leases.models.lease_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='leasefamily',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_family_members', to='leases.lease'),
        ),
        migrations.CreateModel(
            name='LeaseFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('cousin', 'Cousin'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('other', 'Other')], default='other', max_length=30)),
                ('is_adult', models.BooleanField(default=True)),
                ('lives_with_tenant', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_relationships', to='tenants.tenant')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='leases.lease')),
                ('primary_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_family_relationships', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'family_member__first_name', 'family_member__last_name'],
                'constraints': [models.UniqueConstraint(fields=('lease', 'primary_tenant', 'family_member'), name='uniq_lease_primary_family_member')],
            },
        ),
        migrations.RunPython(seed_document_categories, migrations.RunPython.noop),
        migrations.RunPython(copy_legacy_family_members, migrations.RunPython.noop),
    ]
