# Generated by Django 5.2.4 on 2026-06-03 20:13

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_RELATIONSHIP_TYPES = [
    ("Spouse", "spouse", 10),
    ("Son", "son", 20),
    ("Daughter", "daughter", 30),
    ("Father", "father", 40),
    ("Mother", "mother", 50),
    ("Brother", "brother", 60),
    ("Sister", "sister", 70),
    ("Uncle", "uncle", 80),
    ("Aunt", "aunt", 90),
    ("Grandfather", "grandfather", 100),
    ("Grandmother", "grandmother", 110),
    ("Cousin", "cousin", 120),
    ("Nephew", "nephew", 130),
    ("Niece", "niece", 140),
    ("Other", "other", 900),
]


def seed_relationship_types(apps, schema_editor):
    LeaseRelationshipType = apps.get_model("leases", "LeaseRelationshipType")
    LeaseFamilyMember = apps.get_model("leases", "LeaseFamilyMember")

    by_code = {}
    for name, code, sort_order in DEFAULT_RELATIONSHIP_TYPES:
        item, _ = LeaseRelationshipType.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "is_active": True,
            },
        )
        changed = []
        if item.name != name:
            item.name = name
            changed.append("name")
        if item.sort_order != sort_order:
            item.sort_order = sort_order
            changed.append("sort_order")
        if not item.is_active:
            item.is_active = True
            changed.append("is_active")
        if changed:
            item.save(update_fields=changed)
        by_code[code] = item

    fallback = by_code.get("other")
    for link in LeaseFamilyMember.objects.all().iterator():
        code = (link.relationship or "other").strip().lower()
        relationship_type = by_code.get(code, fallback)
        if relationship_type:
            link.relationship_type_id = relationship_type.pk
            link.relationship = relationship_type.code[:30]
            link.save(update_fields=["relationship_type", "relationship"])


def clear_relationship_type_links(apps, schema_editor):
    LeaseFamilyMember = apps.get_model("leases", "LeaseFamilyMember")
    LeaseFamilyMember.objects.update(relationship_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0043_leasedocument_share_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=50)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='leasefamilymember',
            name='relationship',
            field=models.CharField(default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='leasefamilymember',
            name='relationship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='leases.leaserelationshiptype'),
        ),
        migrations.RunPython(seed_relationship_types, clear_relationship_type_links),
    ]
