# Generated by Django 5.2.4 on 2026-06-04 19:39

import django.core.validators
import leases.models
import leases.models_lease_photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0044_leaserelationshiptype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasedocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=leases.models.lease_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'xls', 'xlsx', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='leasemedia',
            name='file',
            field=models.FileField(max_length=255, upload_to=leases.models_lease_photos._upload_tmp, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'gif', 'pdf', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
