# Generated by Django 5.2.4 on 2026-06-04 20:26

import django.core.validators
import leases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0045_alter_leasedocument_file_alter_leasemedia_file'),
        ('properties', '0015_alter_propertymedia_file_alter_unitmedia_file'),
        ('tenants', '0016_alter_tenant_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasedocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=leases.models.lease_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'doc', 'docx'])]),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant', 'status', 'start_date'], name='leases_leas_tenant__73b951_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status'], name='leases_leas_status_d62744_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit'], name='leases_leas_unit_id_a4eecf_idx'),
        ),
    ]
