# Generated by Django 5.2.4 on 2026-06-05 09:48

from django.db import migrations, models


def mark_electricity_default_clauses(apps, schema_editor):
    DefaultClause = apps.get_model("leases", "DefaultClause")
    for clause in DefaultClause.objects.all():
        body = (clause.body or "").lower()
        if "electricity bill" in body and ("owner" in body or "unit" in body):
            clause.category = "electricity"
            clause.save(update_fields=["category"])


def unmark_electricity_default_clauses(apps, schema_editor):
    DefaultClause = apps.get_model("leases", "DefaultClause")
    DefaultClause.objects.filter(category="electricity").update(category="general")


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0046_alter_leasedocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultclause',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('electricity', 'Electricity billed by owner')], default='general', help_text='Electricity clauses are copied only when electricity is billed by owner.', max_length=30),
        ),
        migrations.AddField(
            model_name='lease',
            name='electricity_bill_by_owner',
            field=models.BooleanField(default=True, help_text='Include owner-billed electricity clauses and charge electricity by unit rate.'),
        ),
        migrations.RunPython(
            mark_electricity_default_clauses,
            unmark_electricity_default_clauses,
        ),
    ]
