# Generated by Django 5.2.4 on 2026-06-29 16:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import leases.models_inspections
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_billingprogressjob'),
        ('leases', '0047_defaultclause_category_and_more'),
        ('properties', '0015_alter_propertymedia_file_alter_unitmedia_file'),
        ('tenants', '0017_alter_tenant_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=150)),
                ('status_name', models.CharField(blank=True, max_length=100)),
                ('status_badge_color', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('damage_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=50)),
                ('required', models.BooleanField(default=False)),
                ('allow_photos', models.BooleanField(default=True)),
                ('allow_damage_cost', models.BooleanField(default=True)),
                ('allow_notes', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('badge_color', models.CharField(default='secondary', help_text='Bootstrap color name, e.g. success, warning, danger, info, secondary.', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Inspection statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('display_order', models.PositiveIntegerField(default=50)),
                ('required', models.BooleanField(default=False)),
                ('allow_photos', models.BooleanField(default=True)),
                ('allow_damage_cost', models.BooleanField(default=True)),
                ('allow_notes', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='leases.inspectioncategory')),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=leases.models_inspections.inspection_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='leases.inspectiondetail')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='templates', to='leases.inspectionitem')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('overall_condition', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('tenant_comments', models.TextField(blank=True)),
                ('inspector_comments', models.TextField(blank=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('tenant_signature', models.TextField(blank=True)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('inspector_signature', models.TextField(blank=True)),
                ('inspector_signed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_signature', models.TextField(blank=True)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('public_token', models.CharField(default=leases.models_inspections.inspection_public_token, max_length=64, unique=True)),
                ('public_expires_at', models.DateTimeField(blank=True, null=True)),
                ('public_is_active', models.BooleanField(default=False)),
                ('audit_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lease_inspections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lease_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspection_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='leases.inspectiontemplate')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='leases.inspectiontype')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_inspections', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='leases.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_inspections', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_inspections', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_inspections', to='properties.unit')),
            ],
            options={
                'ordering': ['-inspection_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('electric', 'Electric Meter'), ('water', 'Water Meter'), ('gas', 'Gas Meter')], max_length=20)),
                ('opening_reading', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_reading', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='leases.leaseinspection')),
            ],
            options={
                'ordering': ['meter_type'],
            },
        ),
        migrations.CreateModel(
            name='InspectionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quantity_issued', models.PositiveIntegerField(default=0)),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='leases.leaseinspection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inspectiondetail',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='leases.leaseinspection'),
        ),
        migrations.CreateModel(
            name='InspectionDamageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_description', models.TextField()),
                ('repair_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('charge_tenant', models.BooleanField(default=True)),
                ('generate_invoice', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_damage_charges', to='invoices.invoice')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_charges', to='leases.inspectiondetail')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_charges', to='leases.leaseinspection')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('condition', models.CharField(blank=True, max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='leases.leaseinspection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='inspectionitem',
            constraint=models.UniqueConstraint(fields=('category', 'item_name'), name='uniq_inspection_item_per_category'),
        ),
        migrations.AddIndex(
            model_name='leaseinspection',
            index=models.Index(fields=['lease', 'status', 'inspection_date'], name='leases_leas_lease_i_73c4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseinspection',
            index=models.Index(fields=['public_token', 'public_is_active'], name='leases_leas_public__c01a3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionmeterreading',
            constraint=models.UniqueConstraint(fields=('inspection', 'meter_type'), name='uniq_inspection_meter_type'),
        ),
        migrations.AddIndex(
            model_name='inspectiondetail',
            index=models.Index(fields=['inspection', 'category', 'display_order'], name='leases_insp_inspect_34c6a7_idx'),
        ),
    ]
