# Generated by Django 5.2.4 on 2026-06-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0048_inspectioncategory_inspectiondetail_inspectionstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseinspection',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
