# Generated by Django 5.2.4 on 2026-06-29 18:02

import django.core.validators
import leases.models_inspections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0050_seed_inspection_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionphoto',
            name='image',
            field=models.FileField(upload_to=leases.models_inspections.inspection_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
