# Generated by Django 5.2.4 on 2026-06-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0052_bedroom_bathroom_second_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='item_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
