# Generated by Django 5.2.4 on 2026-07-01 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0055_alter_lease_status_pendingagreementapproval'),
        ('tenants', '0017_alter_tenant_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLeaseFamilyMemberSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('relationship', models.CharField(default='other', max_length=30)),
                ('cnic', models.CharField(max_length=15)),
                ('cnic_digits', models.CharField(db_index=True, max_length=13)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lease_family_pending/photos/')),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to='lease_family_pending/cnic_front/')),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to='lease_family_pending/cnic_back/')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_submission', to='leases.leasefamilymember')),
                ('created_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_family_submissions', to='tenants.tenant')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_family_submissions', to='leases.lease')),
                ('primary_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_family_submissions', to='tenants.tenant')),
                ('relationship_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_family_submissions', to='leases.leaserelationshiptype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_family_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='leases_pend_status_cfa163_idx'), models.Index(fields=['token', 'expires_at'], name='leases_pend_token_1a50b0_idx')],
            },
        ),
    ]
