# Generated by Django 5.2.4 on 2026-07-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0056_pendingleasefamilymembersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingleasefamilymembersubmission',
            name='action',
            field=models.CharField(choices=[('add', 'Add family member'), ('remove', 'Remove family member')], default='add', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingleasefamilymembersubmission',
            name='existing_family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_removal_submissions', to='leases.leasefamilymember'),
        ),
        migrations.AlterField(
            model_name='pendingleasefamilymembersubmission',
            name='cnic',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pendingleasefamilymembersubmission',
            name='cnic_digits',
            field=models.CharField(blank=True, db_index=True, max_length=13),
        ),
    ]
