# Generated by Django 5.2.4 on 2026-07-01 15:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0057_pendingleasefamilymembersubmission_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseLateFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_enabled', models.BooleanField(default=False, help_text='Use custom late fee rules for this lease instead of global settings.')),
                ('late_fee_enabled', models.BooleanField(default=True)),
                ('late_fee_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percent', 'Percentage')], default='fixed', max_length=10)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('late_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('late_fee_grace_days', models.PositiveIntegerField(default=0)),
                ('reminder_interval_days', models.PositiveIntegerField(default=5)),
                ('late_fee_max_reminders', models.PositiveIntegerField(default=0, help_text='0 = unlimited reminders.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_settings', to='leases.lease')),
            ],
            options={
                'verbose_name': 'Lease late fee setting',
                'verbose_name_plural': 'Lease late fee settings',
            },
        ),
    ]
