# Generated by Django 5.2.4 on 2026-07-01 20:27

import leases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0058_leaselatefeesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingleasefamilymembersubmission',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to=leases.models.pending_family_cnic_back_upload_to),
        ),
        migrations.AlterField(
            model_name='pendingleasefamilymembersubmission',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to=leases.models.pending_family_cnic_front_upload_to),
        ),
        migrations.AlterField(
            model_name='pendingleasefamilymembersubmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=leases.models.pending_family_photo_upload_to),
        ),
    ]
