# Generated by Django 5.2.4 on 2026-07-01 21:33

import django.core.validators
import django.db.models.deletion
import leases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0059_alter_pendingleasefamilymembersubmission_cnic_back_and_more'),
        ('tenants', '0018_tenant_family_member_adults_and_more'),
        ('whatsapp', '0011_alter_whatsappexternallinktoken_link_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPoliceVerificationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=leases.models.pending_police_verification_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('public_link', 'Public Link'), ('whatsapp', 'WhatsApp'), ('staff', 'Staff')], default='public_link', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_pending_sources', to='leases.leasedocument')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_police_verifications', to='leases.lease')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_police_verifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_police_verifications', to='tenants.tenant')),
                ('whatsapp_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_verification_submissions', to='whatsapp.pendingwhatsappmedia')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
                'indexes': [models.Index(fields=['lease', 'status', 'submitted_at'], name='leases_pend_lease_i_c2f1c7_idx'), models.Index(fields=['status', 'submitted_at'], name='leases_pend_status_46d096_idx')],
            },
        ),
    ]
