# Generated by Django 5.2.4 on 2026-07-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0060_pendingpoliceverificationsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='bill_water_charges',
            field=models.BooleanField(default=True, help_text='Include water charges in monthly billing control.'),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='bill_water_charges',
            field=models.BooleanField(default=True, help_text='Include water charges in monthly billing control.'),
        ),
    ]
