# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0062_lease_bill_recurring_charges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionitem",
            name="default_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="inspectiondetail",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
