# Generated by Codex on 2026-07-06

from django.db import migrations


def seed_inspection_quantity_items(apps, schema_editor):
    InspectionCategory = apps.get_model("leases", "InspectionCategory")
    InspectionItem = apps.get_model("leases", "InspectionItem")
    InspectionTemplate = apps.get_model("leases", "InspectionTemplate")

    def category(name, order):
        obj, _ = InspectionCategory.objects.get_or_create(
            name=name,
            defaults={"display_order": order, "active": True},
        )
        return obj

    def item(category_obj, name, order, quantity=1):
        obj, created = InspectionItem.objects.get_or_create(
            category=category_obj,
            item_name=name,
            defaults={
                "display_order": order,
                "default_quantity": quantity,
                "required": True,
                "allow_photos": True,
                "allow_damage_cost": True,
                "allow_notes": True,
                "active": True,
            },
        )
        updates = []
        if obj.default_quantity != quantity:
            obj.default_quantity = quantity
            updates.append("default_quantity")
        if not obj.active:
            obj.active = True
            updates.append("active")
        if updates:
            obj.save(update_fields=updates)
        return obj

    bedroom_categories = [
        cat
        for cat in InspectionCategory.objects.filter(active=True).order_by("display_order", "name")
        if cat.name.lower().startswith("bedroom")
    ]
    bathroom_categories = [
        cat
        for cat in InspectionCategory.objects.filter(active=True).order_by("display_order", "name")
        if cat.name.lower().startswith("bathroom")
    ]
    living_room = category("Living Room", 20)
    kitchen = category("Kitchen", 40)
    single_room = category("Single Room", 45)

    added_items = []

    for cat in bedroom_categories:
        added_items.append(item(cat, "Window Curtain Rod", 95, 1))
        added_items.append(item(cat, "Window Lock", 100, 1))
        light = InspectionItem.objects.filter(category=cat, item_name__iexact="Light").first()
        if light and light.default_quantity != 4:
            light.default_quantity = 4
            light.save(update_fields=["default_quantity"])

    for cat in bathroom_categories:
        added_items.append(item(cat, "Muslim Shower", 95, 1))
        light = InspectionItem.objects.filter(category=cat, item_name__iexact="Light").first()
        if light and light.default_quantity != 1:
            light.default_quantity = 1
            light.save(update_fields=["default_quantity"])

    for cat in [living_room, kitchen, single_room]:
        added_items.append(item(cat, "Window Curtain Rod", 95, 1))
        added_items.append(item(cat, "Window Lock", 100, 1))

    for cat in [living_room, single_room]:
        light = InspectionItem.objects.filter(category=cat, item_name__iexact="Light").first()
        if light:
            if light.default_quantity != 4:
                light.default_quantity = 4
                light.save(update_fields=["default_quantity"])
        else:
            added_items.append(item(cat, "Light", 30, 4))

    kitchen_light = InspectionItem.objects.filter(category=kitchen, item_name__iexact="Light").first()
    if kitchen_light and kitchen_light.default_quantity != 1:
        kitchen_light.default_quantity = 1
        kitchen_light.save(update_fields=["default_quantity"])

    for template in InspectionTemplate.objects.filter(active=True).prefetch_related("items__category"):
        existing_categories = {existing.category_id for existing in template.items.all()}
        template_additions = [
            new_item for new_item in added_items if new_item.category_id in existing_categories
        ]
        if template.name.lower() == "room":
            template_additions.extend(
                InspectionItem.objects.filter(category=single_room, active=True).order_by("display_order", "item_name")
            )
        if not template_additions:
            continue
        current_ids = set(template.items.values_list("id", flat=True))
        new_items = [new_item for new_item in template_additions if new_item.pk not in current_ids]
        if new_items:
            template.items.add(*new_items)
        ordered_ids = list(template.item_order or [])
        for new_item in new_items:
            if new_item.pk not in ordered_ids:
                ordered_ids.append(new_item.pk)
        if ordered_ids != (template.item_order or []):
            template.item_order = ordered_ids
            template.save(update_fields=["item_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0063_inspection_quantities"),
    ]

    operations = [
        migrations.RunPython(seed_inspection_quantity_items, migrations.RunPython.noop),
    ]
