# Generated by Django 5.2.4 on 2026-07-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0064_seed_inspection_quantity_items'),
        ('leases', '0065_lease_vehicle_types_and_vehicles'),
    ]

    operations = [
    ]
