# Generated by Django 5.2.4 on 2026-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0066_merge_20260707_1821'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leasevehicle',
            new_name='leases_leas_lease_i_d66a32_idx',
            old_name='leases_leas_lease_i_veh_idx',
        ),
        migrations.RenameIndex(
            model_name='leasevehicle',
            new_name='leases_leas_registr_271af8_idx',
            old_name='leases_leas_reg_no_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingleasevehiclesubmission',
            new_name='leases_pend_lease_i_6a554b_idx',
            old_name='leases_pveh_lease_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingleasevehiclesubmission',
            new_name='leases_pend_status_37cd00_idx',
            old_name='leases_pveh_status_time_idx',
        ),
    ]
