# Generated by Django 5.2.4 on 2026-07-13 16:02

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0074_agreement_legal_layout_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasevehicle',
            name='owner_cnic',
            field=core.model_fields.NormalizedCNICField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pendingleasefamilymembersubmission',
            name='cnic',
            field=core.model_fields.NormalizedCNICField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pendingleasefamilymembersubmission',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingleasevehiclesubmission',
            name='owner_cnic',
            field=core.model_fields.NormalizedCNICField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pendingpoliceverificationsubmission',
            name='phone',
            field=core.model_fields.NormalizedPhoneField(blank=True, max_length=32),
        ),
    ]
