# Generated by Django 5.2.4 on 2026-07-17 22:11

import django.core.validators
from django.db import migrations, models
from calendar import monthrange
from datetime import date, timedelta


def _calculated_end(start_date, months):
    month_index = start_date.month - 1 + months
    year = start_date.year + month_index // 12
    month = month_index % 12 + 1
    day = min(start_date.day, monthrange(year, month)[1])
    return date(year, month, day) - timedelta(days=1)


def _infer_months(start_date, end_date):
    if not start_date or not end_date or end_date < start_date:
        return 11
    for months in range(1, 121):
        if _calculated_end(start_date, months) == end_date:
            return months
    return max(1, round(((end_date - start_date).days + 1) / 30.4375))


def backfill_existing_terms(apps, schema_editor):
    Lease = apps.get_model("leases", "Lease")
    LeaseRenewal = apps.get_model("leases", "LeaseRenewal")
    for model in (Lease, LeaseRenewal):
        rows = list(model.objects.only("id", "start_date", "end_date", "lease_months"))
        for row in rows:
            row.lease_months = _infer_months(row.start_date, row.end_date)
        if rows:
            model.objects.bulk_update(rows, ["lease_months"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0077_proration_integer_backfill_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease_months',
            field=models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Agreement Term (Months)'),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='lease_months',
            field=models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Agreement Term (Months)'),
        ),
        migrations.RunPython(backfill_existing_terms, migrations.RunPython.noop),
    ]
