# Generated by Django 5.2.4 on 2026-07-18 12:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_rename_allocation_to_payment_detail'),
        ('leases', '0082_add_meter_number_to_electricity_clause'),
        ('properties', '0024_backfill_unit_building_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('unit_label', models.CharField(default='item', max_length=30)),
                ('default_quantity', models.PositiveIntegerField(default=0)),
                ('default_condition', models.CharField(blank=True, default='Working order', max_length=120)),
                ('include_in_clause', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='leasevehicle',
            name='parking_slot',
        ),
        migrations.RemoveField(
            model_name='pendingleasevehiclesubmission',
            name='parking_slot',
        ),
        migrations.CreateModel(
            name='ParkingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10)),
                ('unauthorized_parking_penalty', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_policy', to='leases.lease')),
                ('property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_policy', to='properties.property')),
                ('unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_policy', to='properties.unit')),
            ],
            options={
                'verbose_name_plural': 'Parking policies',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('monthly_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='properties.property')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parking_spaces', to='leases.leasevehicletype')),
            ],
            options={
                'ordering': ['property__property_name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LeaseParkingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_monthly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_space_key', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_allocations', to='leases.lease')),
                ('recurring_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_allocation', to='invoices.recurringcharge')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_allocations', to='leases.leasevehicle')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='leases.parkingspace')),
            ],
            options={
                'ordering': ['parking_space__label'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(blank=True, max_length=120)),
                ('is_included', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.inventoryitemdefinition')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='properties.property')),
            ],
            options={
                'ordering': ['item__sort_order', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='UnitInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(blank=True, max_length=120)),
                ('is_included', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.inventoryitemdefinition')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='properties.unit')),
            ],
            options={
                'ordering': ['item__sort_order', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(blank=True, max_length=120)),
                ('is_included', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_source', models.CharField(blank=True, default='unit', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.inventoryitemdefinition')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='leases.lease')),
            ],
            options={
                'ordering': ['item__sort_order', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('lease', 'item'), name='uniq_lease_inventory_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='parkingspace',
            constraint=models.UniqueConstraint(fields=('property', 'label'), name='uniq_parking_space_label'),
        ),
        migrations.AddConstraint(
            model_name='propertyinventoryitem',
            constraint=models.UniqueConstraint(fields=('property', 'item'), name='uniq_property_inventory_item'),
        ),
        migrations.AddConstraint(
            model_name='unitinventoryitem',
            constraint=models.UniqueConstraint(fields=('unit', 'item'), name='uniq_unit_inventory_item'),
        ),
    ]
