# Generated by Django 5.2.4 on 2026-07-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0085_complete_clause_11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultclause',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('electricity', 'Electricity billed by owner'), ('parking', 'Parking Clause')], default='general', help_text='Electricity and parking categories are included only when applicable to the lease.', max_length=30),
        ),
    ]
