# Generated by Django 5.2.4 on 2026-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0098_separate_letter_qr_and_adjust_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserenewal',
            name='include_lease_photos',
            field=models.BooleanField(default=False, help_text='Include saved lease photos in this agreement package.'),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='lease_photo_ids',
            field=models.JSONField(blank=True, default=list, help_text='LeaseMedia IDs selected for this agreement history.'),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='lease_photo_layout',
            field=models.CharField(choices=[('1up', '1 photo per page'), ('2up', '2 photos per page'), ('4up', '4 photos per page')], default='4up', max_length=10),
        ),
        migrations.AddField(
            model_name='leaserenewal',
            name='lease_photo_selection_mode',
            field=models.CharField(choices=[('selected', 'Selected photos'), ('all', 'All eligible photos')], default='selected', max_length=20),
        ),
    ]
