# Generated by Django 5.2.4 on 2026-08-15 01:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0099_leaserenewal_photo_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='electricity_security_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Separate deposit used only for smart-meter electricity credit control.', max_digits=10),
        ),
    ]
