# Generated by Django 5.2.4 on 2026-08-16 10:16

from django.db import migrations, models


def clear_legacy_default_rate(apps, schema_editor):
    Lease = apps.get_model("leases", "Lease")
    Lease.objects.filter(electric_unit_rate=50).update(electric_unit_rate=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0100_lease_electricity_security_deposit'),
        ('core', '0029_alter_globalsettings_unit_rate_per_kwh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='electric_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, help_text='Optional lease electricity-rate override. Override order: Global, Property, Unit, Meter, then Lease; the last nonblank value wins.', max_digits=10, null=True),
        ),
        migrations.RunPython(clear_legacy_default_rate, migrations.RunPython.noop),
    ]
