# Generated by Django 5.2.4 on 2025-07-08 09:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_date', models.DateField()),
                ('due_date', models.DateField()),
                ('distribution_method', models.CharField(choices=[('equal', 'Equal Distribution'), ('per_person', 'Per Person'), ('usage', 'Based on Usage')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Utilities',
                'ordering': ['-billing_date'],
            },
        ),
    ]
